"""Offline scaffold generator.

Produces a *genuinely runnable* minimal project for each known stack as an
in-memory ``{relative_path: contents}`` mapping. The CodeAgent writes these to
disk when the LLM backend is the offline stub, satisfying design rule #1
(delivered != empty) without any network calls.

No I/O happens here — these are pure functions returning dicts of strings.
"""

from __future__ import annotations

import re as _re
from typing import Callable

# ---- README composition ------------------------------------------------------
# A single composer drives every stack's README so each delivered app ships a
# COMPREHENSIVE doc (title + what-it-does from the brief + install + usage +
# features + project structure), not a one-line stub. Each builder supplies the
# stack-specific install/usage/structure; the shared shell guarantees the
# sections and a real description are always present (design rule #1).


def _json_escape(text: str) -> str:
    """Escape a string for safe embedding inside a hand-built JSON literal."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").strip()


def _toml_escape(text: str) -> str:
    """Escape a string for a double-quoted TOML basic string."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").strip()


def _describe(title: str, brief: str) -> str:
    """One-paragraph "what it does" line drawn from the brief, never a stub."""
    text = (brief or "").strip()
    if not text:
        return f"{title} is an application generated by SkyN3t."
    # Keep the brief verbatim as the description so the README reflects the
    # actual request rather than boilerplate.
    return text[0].upper() + text[1:]


def _features_from_brief(brief: str, defaults: list[str]) -> list[str]:
    """Derive a short feature list from the brief, falling back to stack defaults.

    Splits the brief on common conjunctions/punctuation so a request like
    "tracks todos with due dates and priorities" surfaces as bullet points.
    """
    text = (brief or "").strip()
    if not text:
        return list(defaults)
    parts = _re.split(r"\s*(?:,|;| and | with | that |\.)\s*", text)
    feats = [p.strip().rstrip(".") for p in parts if len(p.strip()) >= 4]
    # De-dupe while preserving order; cap so the list stays scannable.
    seen: set[str] = set()
    out: list[str] = []
    for f in feats:
        key = f.lower()
        if key not in seen:
            seen.add(key)
            out.append(f[0].upper() + f[1:])
    out = out[:6]
    return out or list(defaults)


def compose_readme(
    title: str,
    brief: str,
    *,
    stack_label: str,
    install: str,
    usage: str,
    structure: list[tuple[str, str]],
    features: list[str],
    extra: str = "",
) -> str:
    """Assemble a comprehensive README from stack-specific pieces.

    ``structure`` is a list of ``(path, description)`` rows. ``install`` and
    ``usage`` are pre-formatted markdown blocks (typically fenced code).
    """
    feats = _features_from_brief(brief, features)
    desc = _describe(title, brief)
    lines: list[str] = [f"# {title}", ""]
    # Avoid printing the description twice when the title already IS the brief.
    if desc.strip().lower() != title.strip().lower():
        lines += [desc, ""]
    lines += [
        f"Built with **{stack_label}**. Generated by SkyN3t — a runnable, self-contained starter.",
        "",
        "## Features",
        "",
    ]
    lines += [f"- {f}" for f in feats]
    lines += [
        "",
        "## Installation",
        "",
        install.rstrip(),
        "",
        "## Usage",
        "",
        usage.rstrip(),
        "",
        "## Project structure",
        "",
    ]
    for path, desc in structure:
        lines.append(f"- `{path}` — {desc}")
    if extra:
        lines += ["", extra.rstrip()]
    lines += [
        "",
        "## Development",
        "",
        "This project ships with a test suite. Run it after making changes to keep "
        "the app green.",
        "",
        "---",
        "_Generated offline by SkyN3t. Edit freely — it's yours._",
        "",
    ]
    return "\n".join(lines)


def _react_vite(app_name: str, brief: str) -> dict[str, str]:
    title = brief.strip() or app_name
    return {
        "package.json": (
            "{\n"
            f'  "name": "{app_name}",\n'
            '  "private": true,\n'
            '  "version": "0.1.0",\n'
            f'  "description": "{_json_escape(title)}",\n'
            '  "type": "module",\n'
            '  "scripts": {\n'
            '    "dev": "vite",\n'
            '    "build": "vite build",\n'
            '    "preview": "vite preview"\n'
            "  },\n"
            '  "dependencies": {\n'
            '    "react": "^18.2.0",\n'
            '    "react-dom": "^18.2.0"\n'
            "  },\n"
            '  "devDependencies": {\n'
            '    "@vitejs/plugin-react": "^4.2.0",\n'
            '    "vite": "^5.0.0"\n'
            "  }\n"
            "}\n"
        ),
        "vite.config.js": (
            "import { defineConfig } from 'vite'\n"
            "import react from '@vitejs/plugin-react'\n\n"
            "export default defineConfig({\n"
            "  plugins: [react()],\n"
            "})\n"
        ),
        "index.html": (
            "<!doctype html>\n"
            '<html lang="en">\n'
            "  <head>\n"
            '    <meta charset="UTF-8" />\n'
            '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
            f"    <title>{title}</title>\n"
            "  </head>\n"
            "  <body>\n"
            '    <div id="root"></div>\n'
            '    <script type="module" src="/src/main.jsx"></script>\n'
            "  </body>\n"
            "</html>\n"
        ),
        "src/main.jsx": (
            "import React from 'react'\n"
            "import ReactDOM from 'react-dom/client'\n"
            "import App from './App.jsx'\n"
            "import './styles.css'\n\n"
            "ReactDOM.createRoot(document.getElementById('root')).render(\n"
            "  <React.StrictMode>\n"
            "    <App />\n"
            "  </React.StrictMode>,\n"
            ")\n"
        ),
        "src/App.jsx": (
            "import { useState } from 'react'\n\n"
            "export default function App() {\n"
            "  const [count, setCount] = useState(0)\n"
            "  return (\n"
            '    <main className="app">\n'
            f"      <h1>{title}</h1>\n"
            "      <p>A runnable Vite + React starter generated offline by SkyN3t.</p>\n"
            '      <button onClick={() => setCount((c) => c + 1)}>\n'
            "        count is {count}\n"
            "      </button>\n"
            "    </main>\n"
            "  )\n"
            "}\n"
        ),
        "src/styles.css": (
            ":root { font-family: system-ui, sans-serif; }\n"
            "body { margin: 0; display: grid; place-items: center; min-height: 100vh; }\n"
            ".app { text-align: center; padding: 2rem; }\n"
            "button { font-size: 1rem; padding: 0.5rem 1rem; cursor: pointer; }\n"
        ),
        ".gitignore": "node_modules\ndist\n",
        "README.md": compose_readme(
            title,
            brief,
            stack_label="Vite + React",
            install="```bash\nnpm install\n```\n\nRequires Node.js 18+.",
            usage=(
                "Start the dev server with hot-reload:\n\n"
                "```bash\nnpm run dev\n```\n\n"
                "Build a production bundle and preview it:\n\n"
                "```bash\nnpm run build\nnpm run preview\n```"
            ),
            structure=[
                ("index.html", "HTML entry that mounts the React app"),
                ("src/main.jsx", "React bootstrap — renders <App /> into #root"),
                ("src/App.jsx", "Root component (extend this with your UI)"),
                ("src/styles.css", "Global styles"),
                ("vite.config.js", "Vite + React plugin configuration"),
                ("package.json", "Dependencies and npm scripts"),
            ],
            features=[
                "Vite dev server with instant hot-module reload",
                "React 18 component architecture",
                "Production build + preview scripts",
            ],
        ),
    }


def _static_html(app_name: str, brief: str) -> dict[str, str]:
    title = brief.strip() or app_name
    return {
        "index.html": (
            "<!doctype html>\n"
            '<html lang="en">\n'
            "  <head>\n"
            '    <meta charset="UTF-8" />\n'
            '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
            f"    <title>{title}</title>\n"
            '    <link rel="stylesheet" href="styles.css" />\n'
            "  </head>\n"
            "  <body>\n"
            f"    <main><h1>{title}</h1>\n"
            "    <p>A runnable static site generated offline by SkyN3t.</p>\n"
            '    <button id="cta">Click me</button></main>\n'
            '    <script src="main.js"></script>\n'
            "  </body>\n"
            "</html>\n"
        ),
        "styles.css": (
            "body { font-family: system-ui, sans-serif; display: grid;"
            " place-items: center; min-height: 100vh; margin: 0; }\n"
            "main { text-align: center; }\n"
        ),
        "main.js": (
            "let count = 0;\n"
            "const btn = document.getElementById('cta');\n"
            "btn.addEventListener('click', () => {\n"
            "  count += 1;\n"
            "  btn.textContent = `Clicked ${count} times`;\n"
            "});\n"
        ),
        "package.json": (
            "{\n"
            f'  "name": "{app_name}",\n'
            '  "private": true,\n'
            '  "version": "0.1.0",\n'
            f'  "description": "{_json_escape(title)}",\n'
            '  "scripts": {\n'
            '    "start": "npx serve .",\n'
            '    "dev": "npx serve ."\n'
            "  },\n"
            '  "dependencies": {},\n'
            '  "devDependencies": {\n'
            '    "serve": "^14.2.1"\n'
            "  }\n"
            "}\n"
        ),
        "README.md": compose_readme(
            title,
            brief,
            stack_label="static HTML + CSS + JavaScript",
            install=(
                "No build step. Either open `index.html` directly, or for a local "
                "server (recommended for correct paths):\n\n"
                "```bash\nnpm install\n```"
            ),
            usage=(
                "Open the site in a browser by double-clicking `index.html`, or "
                "serve it locally:\n\n"
                "```bash\nnpm start\n```\n\n"
                "Then visit the printed `http://localhost` URL."
            ),
            structure=[
                ("index.html", "Page markup and entry point"),
                ("styles.css", "Stylesheet"),
                ("main.js", "Client-side behavior"),
                ("package.json", "Optional local-server tooling"),
            ],
            features=[
                "Zero build step — pure HTML, CSS, and JS",
                "Loads instantly in any modern browser",
                "Optional local static server via npm",
            ],
        ),
    }


def _python_cli(app_name: str, brief: str) -> dict[str, str]:
    pkg = (app_name.replace("-", "_").strip() or "app")
    # a valid python identifier for the package dir
    if not pkg[0].isalpha() and pkg[0] != "_":
        pkg = f"app_{pkg}"
    title = brief.strip() or app_name
    return {
        "pyproject.toml": (
            "[project]\n"
            f'name = "{app_name}"\n'
            'version = "0.1.0"\n'
            f'description = "{_toml_escape(title)}"\n'
            'requires-python = ">=3.10"\n'
            "# Runtime dependencies. The stdlib (argparse) covers the starter; add\n"
            "# real packages here as the tool grows.\n"
            "dependencies = []\n\n"
            "[project.optional-dependencies]\n"
            '# `pip install -e ".[dev]"` to get the test/lint toolchain.\n'
            'dev = ["pytest>=7", "ruff>=0.1"]\n\n'
            "[project.scripts]\n"
            f'{app_name} = "{pkg}.cli:main"\n\n'
            "[build-system]\n"
            'requires = ["setuptools>=61"]\n'
            'build-backend = "setuptools.build_meta"\n'
        ),
        "requirements.txt": (
            "# Runtime dependencies for "
            f"{title}.\n"
            "# The starter relies only on the Python standard library; pin real\n"
            "# packages below as you add them (one per line).\n"
        ),
        "main.py": (
            '"""Root entrypoint: ``python main.py`` runs the CLI."""\n'
            "from __future__ import annotations\n\n"
            f"from {pkg}.cli import main\n\n\n"
            'if __name__ == "__main__":\n'
            "    raise SystemExit(main())\n"
        ),
        f"{pkg}/__init__.py": (
            f'"""{title} — generated offline by SkyN3t."""\n\n'
            '__version__ = "0.1.0"\n'
        ),
        f"{pkg}/core.py": (
            '"""Core logic for the tool (pure, easily testable)."""\n'
            "from __future__ import annotations\n\n\n"
            "def greet(name: str) -> str:\n"
            '    """Return a friendly greeting."""\n'
            "    name = (name or \"world\").strip() or \"world\"\n"
            '    return f"Hello, {name}!"\n'
        ),
        f"{pkg}/cli.py": (
            '"""Command-line interface."""\n'
            "from __future__ import annotations\n\n"
            "import argparse\n\n"
            f"from {pkg}.core import greet\n\n\n"
            "def build_parser() -> argparse.ArgumentParser:\n"
            f'    parser = argparse.ArgumentParser(prog="{app_name}", description="{title}")\n'
            '    parser.add_argument("--name", default="world", help="who to greet")\n'
            "    return parser\n\n\n"
            "def main(argv: list[str] | None = None) -> int:\n"
            "    args = build_parser().parse_args(argv)\n"
            "    print(greet(args.name))\n"
            "    return 0\n\n\n"
            'if __name__ == "__main__":\n'
            "    raise SystemExit(main())\n"
        ),
        "tests/test_core.py": (
            f"from {pkg}.core import greet\n\n\n"
            "def test_greet_default():\n"
            '    assert greet("world") == "Hello, world!"\n\n\n'
            "def test_greet_strips():\n"
            '    assert greet("  ada ") == "Hello, ada!"\n'
        ),
        "README.md": compose_readme(
            title,
            brief,
            stack_label="Python CLI",
            install=(
                "Requires Python 3.10+. Install in a virtual environment:\n\n"
                "```bash\n"
                "python -m venv .venv\n"
                "source .venv/bin/activate   # Windows: .venv\\Scripts\\activate\n"
                'pip install -e ".[dev]"\n'
                "```"
            ),
            usage=(
                "Run directly:\n\n"
                "```bash\npython main.py --name you\n```\n\n"
                f"Or, once installed, via the `{app_name}` console script:\n\n"
                f"```bash\n{app_name} --name you\n```\n\n"
                "Use `--help` to list all options."
            ),
            structure=[
                ("main.py", "Root entrypoint — `python main.py` runs the CLI"),
                (f"{pkg}/cli.py", "Argument parsing and command dispatch"),
                (f"{pkg}/core.py", "Pure, testable core logic"),
                (f"{pkg}/__init__.py", "Package metadata"),
                ("tests/test_core.py", "Unit tests for the core logic"),
                ("pyproject.toml", "Build config, console script, and dependencies"),
            ],
            features=[
                "Argparse-based command-line interface",
                "Separated pure core logic for easy testing",
                "Installable console script entry point",
            ],
            extra=(
                "### Tests\n\n"
                "```bash\npytest\n```"
            ),
        ),
        ".gitignore": "__pycache__/\n*.pyc\n.venv/\ndist/\n*.egg-info/\n",
    }


def _fastapi(app_name: str, brief: str) -> dict[str, str]:
    title = brief.strip() or app_name
    return {
        "main.py": (
            '"""' + f"{title} — a runnable FastAPI app generated offline by SkyN3t." + '"""\n\n'
            "from __future__ import annotations\n\n"
            "from fastapi import FastAPI\n\n"
            'app = FastAPI(title="' + title + '")\n\n\n'
            '@app.get("/")\n'
            "async def root() -> dict[str, str]:\n"
            '    return {"message": "' + title + ' is running"}\n\n\n'
            '@app.get("/health")\n'
            "async def health() -> dict[str, str]:\n"
            '    return {"status": "ok"}\n'
        ),
        "test_main.py": (
            "from fastapi.testclient import TestClient\n\n"
            "from main import app\n\n"
            "client = TestClient(app)\n\n\n"
            "def test_health():\n"
            '    resp = client.get("/health")\n'
            "    assert resp.status_code == 200\n"
            '    assert resp.json()["status"] == "ok"\n'
        ),
        "requirements.txt": (
            f"# Runtime + test dependencies for {title}.\n"
            "fastapi>=0.110        # web framework\n"
            "uvicorn[standard]>=0.27  # ASGI server (run with `uvicorn main:app`)\n"
            "httpx>=0.27           # used by fastapi.testclient for the test suite\n"
        ),
        "README.md": compose_readme(
            title,
            brief,
            stack_label="FastAPI",
            install=(
                "Requires Python 3.10+. Install dependencies into a virtual env:\n\n"
                "```bash\n"
                "python -m venv .venv\n"
                "source .venv/bin/activate   # Windows: .venv\\Scripts\\activate\n"
                "pip install -r requirements.txt\n"
                "```"
            ),
            usage=(
                "Run the development server with auto-reload:\n\n"
                "```bash\nuvicorn main:app --reload\n```\n\n"
                "The API is then available at `http://127.0.0.1:8000`:\n\n"
                "- `GET /` — service status\n"
                "- `GET /health` — health check\n"
                "- `GET /docs` — interactive OpenAPI docs (Swagger UI)"
            ),
            structure=[
                ("main.py", "FastAPI application and route handlers"),
                ("test_main.py", "API tests via fastapi.testclient"),
                ("requirements.txt", "Runtime and test dependencies"),
            ],
            features=[
                "FastAPI app with health and root endpoints",
                "Auto-generated OpenAPI / Swagger docs at /docs",
                "Test suite using the built-in TestClient",
            ],
            extra=(
                "### Tests\n\n"
                "```bash\npytest\n```"
            ),
        ),
    }


def _node_express(app_name: str, brief: str) -> dict[str, str]:
    title = brief.strip() or app_name
    return {
        "package.json": (
            "{\n"
            f'  "name": "{app_name}",\n'
            '  "version": "0.1.0",\n'
            f'  "description": "{_json_escape(title)}",\n'
            '  "type": "commonjs",\n'
            '  "main": "server.js",\n'
            '  "scripts": {\n'
            '    "start": "node server.js",\n'
            '    "test": "node test.js"\n'
            "  },\n"
            '  "dependencies": { "express": "^4.18.2" }\n'
            "}\n"
        ),
        "server.js": (
            "const express = require('express');\n"
            "const app = express();\n"
            "const port = process.env.PORT || 3000;\n\n"
            "app.get('/', (req, res) => res.json({ message: '" + title + " is running' }));\n"
            "app.get('/health', (req, res) => res.json({ status: 'ok' }));\n\n"
            "if (require.main === module) {\n"
            "  app.listen(port, () => console.log(`listening on ${port}`));\n"
            "}\n"
            "module.exports = app;\n"
        ),
        "test.js": (
            "const assert = require('assert');\n"
            "const app = require('./server.js');\n\n"
            "assert.strictEqual(typeof app, 'function', 'server.js must export the express app');\n"
            "console.log('ok');\n"
        ),
        ".gitignore": "node_modules\n",
        "README.md": compose_readme(
            title,
            brief,
            stack_label="Node.js + Express",
            install="```bash\nnpm install\n```\n\nRequires Node.js 18+.",
            usage=(
                "Start the server:\n\n"
                "```bash\nnpm start\n```\n\n"
                "It listens on `http://localhost:3000` (override with the `PORT` "
                "environment variable):\n\n"
                "- `GET /` — service status\n"
                "- `GET /health` — health check"
            ),
            structure=[
                ("server.js", "Express app, routes, and server bootstrap"),
                ("test.js", "Smoke test asserting the app exports correctly"),
                ("package.json", "Dependencies and npm scripts"),
            ],
            features=[
                "Express HTTP server with health and root routes",
                "Configurable port via the PORT env var",
                "Exports the app for testing/embedding",
            ],
            extra=(
                "### Tests\n\n"
                "```bash\nnpm test\n```"
            ),
        ),
    }


def _react_native_expo(app_name: str, brief: str) -> dict[str, str]:
    """A genuinely runnable minimal Expo (React Native + TypeScript) app.

    Mobile can't be iframe-previewed like the web stacks, so the proof for this
    stack is a type-check (``npm run typecheck`` -> ``tsc --noEmit``) rather than
    a dev server. The app ships a real default-exported root screen with a
    reusable component and local state, plus a test, so ``delivered != empty``.
    """
    title = brief.strip() or app_name
    # A JSON-safe display title (for app.json) and a JS-string-literal title (for
    # the JSX), plus a slug for the Expo config.
    safe_title = title.replace('"', "'")
    js_title = title.replace("\\", "\\\\").replace("'", "\\'")
    slug = _re.sub(r"[^a-z0-9-]+", "-", app_name.lower()).strip("-") or "app"
    return {
        "package.json": (
            "{\n"
            f'  "name": "{slug}",\n'
            '  "version": "0.1.0",\n'
            '  "private": true,\n'
            '  "main": "node_modules/expo/AppEntry.js",\n'
            '  "scripts": {\n'
            '    "start": "expo start",\n'
            '    "android": "expo start --android",\n'
            '    "ios": "expo start --ios",\n'
            '    "typecheck": "tsc --noEmit",\n'
            '    "test": "jest"\n'
            "  },\n"
            '  "dependencies": {\n'
            '    "expo": "~51.0.0",\n'
            '    "expo-status-bar": "~1.12.1",\n'
            '    "react": "18.2.0",\n'
            '    "react-native": "0.74.5"\n'
            "  },\n"
            '  "devDependencies": {\n'
            '    "@types/react": "~18.2.45",\n'
            '    "typescript": "~5.3.3"\n'
            "  }\n"
            "}\n"
        ),
        "app.json": (
            "{\n"
            '  "expo": {\n'
            f'    "name": "{safe_title}",\n'
            f'    "slug": "{slug}",\n'
            '    "version": "1.0.0",\n'
            '    "orientation": "portrait",\n'
            '    "userInterfaceStyle": "light",\n'
            '    "splash": {\n'
            '      "resizeMode": "contain",\n'
            '      "backgroundColor": "#ffffff"\n'
            "    },\n"
            '    "ios": { "supportsTablet": true },\n'
            '    "android": {},\n'
            '    "web": { "bundler": "metro" }\n'
            "  }\n"
            "}\n"
        ),
        "tsconfig.json": (
            "{\n"
            '  "extends": "expo/tsconfig.base",\n'
            '  "compilerOptions": {\n'
            '    "strict": true,\n'
            '    "jsx": "react-native",\n'
            '    "esModuleInterop": true,\n'
            '    "skipLibCheck": true\n'
            "  }\n"
            "}\n"
        ),
        "babel.config.js": (
            "module.exports = function (api) {\n"
            "  api.cache(true);\n"
            "  return {\n"
            "    presets: ['babel-preset-expo'],\n"
            "  };\n"
            "};\n"
        ),
        "App.tsx": (
            "import { useState } from 'react';\n"
            "import { StatusBar } from 'expo-status-bar';\n"
            "import { StyleSheet, Text, View } from 'react-native';\n\n"
            "import { Counter } from './src/components/Counter';\n\n"
            "export default function App(): JSX.Element {\n"
            "  const [taps, setTaps] = useState(0);\n"
            "  return (\n"
            "    <View style={styles.container}>\n"
            "      <Text style={styles.title}>{'" + js_title + "'}</Text>\n"
            "      <Text style={styles.subtitle}>\n"
            "        A runnable Expo app generated offline by SkyN3t.\n"
            "      </Text>\n"
            "      <Counter value={taps} onPress={() => setTaps((n) => n + 1)} />\n"
            "      <StatusBar style=\"auto\" />\n"
            "    </View>\n"
            "  );\n"
            "}\n\n"
            "const styles = StyleSheet.create({\n"
            "  container: {\n"
            "    flex: 1,\n"
            "    backgroundColor: '#fff',\n"
            "    alignItems: 'center',\n"
            "    justifyContent: 'center',\n"
            "    padding: 24,\n"
            "  },\n"
            "  title: { fontSize: 24, fontWeight: '600', marginBottom: 8 },\n"
            "  subtitle: { fontSize: 14, color: '#555', textAlign: 'center', marginBottom: 24 },\n"
            "});\n"
        ),
        "src/components/Counter.tsx": (
            "import { Pressable, StyleSheet, Text } from 'react-native';\n\n"
            "export interface CounterProps {\n"
            "  value: number;\n"
            "  onPress: () => void;\n"
            "}\n\n"
            "export function Counter({ value, onPress }: CounterProps): JSX.Element {\n"
            "  return (\n"
            "    <Pressable accessibilityRole=\"button\" style={styles.button} onPress={onPress}>\n"
            "      <Text style={styles.label}>Tapped {value} times</Text>\n"
            "    </Pressable>\n"
            "  );\n"
            "}\n\n"
            "const styles = StyleSheet.create({\n"
            "  button: {\n"
            "    backgroundColor: '#1f6feb',\n"
            "    paddingHorizontal: 20,\n"
            "    paddingVertical: 12,\n"
            "    borderRadius: 8,\n"
            "  },\n"
            "  label: { color: '#fff', fontSize: 16 },\n"
            "});\n"
        ),
        "__tests__/App.test.tsx": (
            "import { Counter } from '../src/components/Counter';\n\n"
            "// A lightweight smoke test: the component is a function and accepts\n"
            "// the documented props. (Full render tests need @testing-library/\n"
            "// react-native, which we keep out of the offline scaffold.)\n"
            "describe('Counter', () => {\n"
            "  it('is a renderable component function', () => {\n"
            "    expect(typeof Counter).toBe('function');\n"
            "  });\n"
            "});\n"
        ),
        ".gitignore": "node_modules/\n.expo/\ndist/\nweb-build/\n*.log\n",
        "README.md": compose_readme(
            title,
            brief,
            stack_label="Expo + React Native + TypeScript",
            install=(
                "```bash\nnpm install\n```\n\n"
                "Requires Node.js 18+ and the Expo CLI (`npx expo`)."
            ),
            usage=(
                "Start the app (opens the Expo dev tools):\n\n"
                "```bash\nnpm start\n```\n\n"
                "Then press `i` for the iOS simulator, `a` for Android, or scan the QR "
                "code with the Expo Go app on your phone. Type-check the app:\n\n"
                "```bash\nnpm run typecheck\n```"
            ),
            structure=[
                ("App.tsx", "Root screen — default-exported <App />, wires the UI together"),
                ("src/components/Counter.tsx", "Reusable component with typed props + local state"),
                ("app.json", "Expo app config (name, slug, platforms)"),
                ("package.json", "Dependencies and npm scripts (start, ios, android, typecheck)"),
                ("tsconfig.json", "TypeScript config (extends expo/tsconfig.base)"),
                ("babel.config.js", "Babel preset for Expo"),
                ("__tests__/App.test.tsx", "Smoke test for the Counter component"),
            ],
            features=[
                "Cross-platform iOS + Android from one codebase via Expo",
                "TypeScript with a reusable, typed component",
                "Local state with React hooks",
                "Type-checked (tsc --noEmit) instead of a web dev-server preview",
            ],
            extra=(
                "> **Note:** mobile apps run on a device/simulator and cannot be "
                "previewed in an iframe like the web stacks. The proof for this stack "
                "is a type check (`npm run typecheck`), not a dev-server boot."
            ),
        ),
    }


_BUILDERS: dict[str, Callable[[str, str], dict[str, str]]] = {
    "react_vite": _react_vite,
    "react_native": _react_native_expo,
    "static_html": _static_html,
    "python_cli": _python_cli,
    "fastapi": _fastapi,
    "node_express": _node_express,
}


def scaffold_for(stack: str, app_name: str, brief: str = "") -> dict[str, str]:
    """Return a ``{path: contents}`` mapping for a runnable project of ``stack``.

    Unknown stacks fall back to ``react_vite``.
    """
    builder = _BUILDERS.get(stack, _react_vite)
    safe_name = (app_name or "app").strip() or "app"
    return builder(safe_name, brief)


# ---- entrypoint synthesis (repair an agentic build with no runnable root) ----
# A coding agent often authors a real package (foo/manager.py, foo/cli.py, …)
# but forgets the runnable ROOT the rest of the pipeline (proof, boot, reviewer)
# expects. These pure helpers detect that and synthesize a real, wired
# ``main.py`` so ``python main.py`` actually runs the produced code — instead of
# the old behaviour of papering over it with an empty stub.

_ENTRYPOINT_BASENAMES = frozenset(
    {"main.py", "__main__.py", "app.py", "cli.py", "run.py", "manage.py", "wsgi.py", "asgi.py"}
)
# Module-level only (no leading indent): an indented ``def main(self)`` inside a
# class is a method, not an importable ``from module import main`` symbol.
_DEF_ENTRY_RE = _re.compile(r"^def\s+(main|run|cli)\s*\(", _re.MULTILINE)


def _norm(rel: str) -> str:
    return rel.replace("\\", "/")


def _module_path(rel: str) -> str:
    rel = _norm(rel)
    return rel[:-3].replace("/", ".") if rel.endswith(".py") else rel


def has_python_entrypoint(files: dict[str, str]) -> bool:
    """True if any file looks like a runnable Python entrypoint."""
    for rel in files:
        base = _norm(rel).rsplit("/", 1)[-1]
        if base in _ENTRYPOINT_BASENAMES:
            return True
    return False


def top_level_packages(files: dict[str, str]) -> list[str]:
    """Names of depth-1 packages (a dir directly holding ``__init__.py``)."""
    pkgs = {
        _norm(rel).split("/")[0]
        for rel in files
        if len(_norm(rel).split("/")) == 2 and _norm(rel).endswith("/__init__.py")
    }
    return sorted(pkgs)


def _find_entry_callable(files: dict[str, str]) -> tuple[str, str] | None:
    """Find a ``module, func`` exposing a callable named main/run/cli."""

    def rank(rel: str) -> int:
        base = _norm(rel).rsplit("/", 1)[-1]
        return {"cli.py": 0, "__main__.py": 1, "app.py": 2, "main.py": 3}.get(base, 9)

    for rel in sorted(files, key=rank):
        if not _norm(rel).endswith(".py"):
            continue
        m = _DEF_ENTRY_RE.search(files[rel] or "")
        if m:
            return _module_path(rel), m.group(1)
    return None


def synthesize_python_entrypoint(files: dict[str, str]) -> dict[str, str]:
    """Return ``{"main.py": <shim>}`` wiring an existing package to a root runner.

    Returns ``{}`` when the tree already has an entrypoint or there is nothing to
    wire. The shim imports the produced code so ``python main.py`` is genuinely
    runnable (and importable by the boot/proof checks).
    """
    if has_python_entrypoint(files):
        return {}
    target = _find_entry_callable(files)
    pkgs = top_level_packages(files)
    if target is None and not pkgs:
        return {}

    if target is not None:
        module, func = target
        shim = (
            '"""Application entrypoint (auto-wired by SkyN3t).\n\n'
            f"Delegates to ``{module}.{func}`` so ``python main.py`` runs the app.\n"
            '"""\n'
            "from __future__ import annotations\n\n"
            f"from {module} import {func} as _entry\n\n\n"
            "def main(argv: list[str] | None = None) -> int:\n"
            "    result = _entry()\n"
            "    return result if isinstance(result, int) else 0\n\n\n"
            'if __name__ == "__main__":\n'
            "    raise SystemExit(main())\n"
        )
        return {"main.py": shim}

    pkg = pkgs[0]
    shim = (
        '"""Application entrypoint (auto-generated by SkyN3t).\n\n'
        f"Best-effort runner: imports the ``{pkg}`` package and invokes its\n"
        "main()/run()/cli() if one exists.\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        "import importlib\n\n"
        "_MODULES = (\n"
        f'    "{pkg}.cli",\n'
        f'    "{pkg}.__main__",\n'
        f'    "{pkg}.main",\n'
        f'    "{pkg}.app",\n'
        f'    "{pkg}",\n'
        ")\n"
        '_FUNCS = ("main", "run", "cli")\n\n\n'
        "def _resolve():\n"
        "    for name in _MODULES:\n"
        "        try:\n"
        "            mod = importlib.import_module(name)\n"
        "        except Exception:\n"
        "            continue\n"
        "        for fn in _FUNCS:\n"
        "            cand = getattr(mod, fn, None)\n"
        "            if callable(cand):\n"
        "                return cand\n"
        "    return None\n\n\n"
        "def main(argv: list[str] | None = None) -> int:\n"
        "    entry = _resolve()\n"
        "    if entry is None:\n"
        f'        print("{pkg}: imported OK, but no main()/run()/cli() entrypoint was found.")\n'
        "        return 0\n"
        "    result = entry()\n"
        "    return result if isinstance(result, int) else 0\n\n\n"
        'if __name__ == "__main__":\n'
        "    raise SystemExit(main())\n"
    )
    return {"main.py": shim}


def default_pyproject(slug: str) -> str:
    """A minimal but real pyproject for a python project keyed off the slug."""
    name = (slug or "app").strip() or "app"
    return (
        "[project]\n"
        f'name = "{name}"\n'
        'version = "0.1.0"\n'
        'requires-python = ">=3.10"\n\n'
        "[project.scripts]\n"
        f'{name} = "main:main"\n'
    )
