"""Offline scaffold generator.

Produces a *genuinely runnable* minimal project for each known stack as an
in-memory ``{relative_path: contents}`` mapping. The CodeAgent writes these to
disk when the LLM backend is the offline stub, satisfying design rule #1
(delivered != empty) without any network calls.

No I/O happens here — these are pure functions returning dicts of strings.
"""

from __future__ import annotations

import re as _re
from collections.abc import Callable

# ---- README composition ------------------------------------------------------
# A single composer drives every stack's README so each delivered app ships a
# COMPREHENSIVE doc (title + what-it-does from the brief + install + usage +
# features + project structure), not a one-line stub. Each builder supplies the
# stack-specific install/usage/structure; the shared shell guarantees the
# sections and a real description are always present (design rule #1).


def _json_escape(text: str) -> str:
    """Escape a string for safe embedding inside a hand-built JSON literal."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").strip()


def _toml_escape(text: str) -> str:
    """Escape a string for a double-quoted TOML basic string."""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", " ").strip()


def _describe(title: str, brief: str) -> str:
    """One-paragraph "what it does" line drawn from the brief, never a stub."""
    text = (brief or "").strip()
    if not text:
        return f"{title} is an application generated by SkyN3t."
    # Keep the brief verbatim as the description so the README reflects the
    # actual request rather than boilerplate.
    return text[0].upper() + text[1:]


def _features_from_brief(brief: str, defaults: list[str]) -> list[str]:
    """Derive a short feature list from the brief, falling back to stack defaults.

    Splits the brief on common conjunctions/punctuation so a request like
    "tracks todos with due dates and priorities" surfaces as bullet points.
    """
    text = (brief or "").strip()
    if not text:
        return list(defaults)
    parts = _re.split(r"\s*(?:,|;| and | with | that |\.)\s*", text)
    feats = [p.strip().rstrip(".") for p in parts if len(p.strip()) >= 4]
    # De-dupe while preserving order; cap so the list stays scannable.
    seen: set[str] = set()
    out: list[str] = []
    for f in feats:
        key = f.lower()
        if key not in seen:
            seen.add(key)
            out.append(f[0].upper() + f[1:])
    out = out[:6]
    return out or list(defaults)


def compose_readme(
    title: str,
    brief: str,
    *,
    stack_label: str,
    install: str,
    usage: str,
    structure: list[tuple[str, str]],
    features: list[str],
    extra: str = "",
) -> str:
    """Assemble a comprehensive README from stack-specific pieces.

    ``structure`` is a list of ``(path, description)`` rows. ``install`` and
    ``usage`` are pre-formatted markdown blocks (typically fenced code).
    """
    feats = _features_from_brief(brief, features)
    desc = _describe(title, brief)
    lines: list[str] = [f"# {title}", ""]
    # Avoid printing the description twice when the title already IS the brief.
    if desc.strip().lower() != title.strip().lower():
        lines += [desc, ""]
    lines += [
        f"Built with **{stack_label}**. Generated by SkyN3t — a runnable, self-contained starter.",
        "",
        "## Features",
        "",
    ]
    lines += [f"- {f}" for f in feats]
    lines += [
        "",
        "## Installation",
        "",
        install.rstrip(),
        "",
        "## Usage",
        "",
        usage.rstrip(),
        "",
        "## Project structure",
        "",
    ]
    for path, desc in structure:
        lines.append(f"- `{path}` — {desc}")
    if extra:
        lines += ["", extra.rstrip()]
    lines += [
        "",
        "## Development",
        "",
        "This project ships with a test suite. Run it after making changes to keep "
        "the app green.",
        "",
        "---",
        "_Generated offline by SkyN3t. Edit freely — it's yours._",
        "",
    ]
    return "\n".join(lines)


# ---- Three.js template detection --------------------------------------------
# Three.js is NOT a stack — it's a TEMPLATE variant of the react/static web
# scaffolds. When the brief implies 3D/WebGL we swap the starter component/page
# for a rotating-cube Three.js scene and add ``three`` as a dependency. The guard
# is keyword-based so ordinary react/static builds are completely unchanged.
_THREEJS_KEYWORDS = ("three.js", "threejs", "three js", "webgl", "3d", "3-d")


def _implies_3d(brief: str) -> bool:
    """True when the brief asks for a 3D / Three.js / WebGL experience."""
    low = (brief or "").lower()
    return any(k in low for k in _THREEJS_KEYWORDS)


def _react_vite(app_name: str, brief: str) -> dict[str, str]:
    title = brief.strip() or app_name
    # JSX-significant chars in the brief (<, >, {, }, ', \) otherwise produce an
    # uncompilable App.jsx; escape for the JS-string and HTML contexts like the
    # nextjs/astro builders do.
    js_title = title.replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ").replace("\r", " ")
    html_title = title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return {
        "package.json": (
            "{\n"
            f'  "name": "{app_name}",\n'
            '  "private": true,\n'
            '  "version": "0.1.0",\n'
            f'  "description": "{_json_escape(title)}",\n'
            '  "type": "module",\n'
            '  "scripts": {\n'
            '    "dev": "vite",\n'
            '    "build": "vite build",\n'
            '    "preview": "vite preview"\n'
            "  },\n"
            '  "dependencies": {\n'
            '    "react": "^18.2.0",\n'
            '    "react-dom": "^18.2.0"\n'
            "  },\n"
            '  "devDependencies": {\n'
            '    "@vitejs/plugin-react": "^4.2.0",\n'
            '    "vite": "^5.0.0"\n'
            "  }\n"
            "}\n"
        ),
        "vite.config.js": (
            "import { defineConfig } from 'vite'\n"
            "import react from '@vitejs/plugin-react'\n\n"
            "export default defineConfig({\n"
            "  plugins: [react()],\n"
            "})\n"
        ),
        "index.html": (
            "<!doctype html>\n"
            '<html lang="en">\n'
            "  <head>\n"
            '    <meta charset="UTF-8" />\n'
            '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
            f"    <title>{html_title}</title>\n"
            "  </head>\n"
            "  <body>\n"
            '    <div id="root"></div>\n'
            '    <script type="module" src="/src/main.jsx"></script>\n'
            "  </body>\n"
            "</html>\n"
        ),
        "src/main.jsx": (
            "import React from 'react'\n"
            "import ReactDOM from 'react-dom/client'\n"
            "import App from './App.jsx'\n"
            "import './styles.css'\n\n"
            "ReactDOM.createRoot(document.getElementById('root')).render(\n"
            "  <React.StrictMode>\n"
            "    <App />\n"
            "  </React.StrictMode>,\n"
            ")\n"
        ),
        "src/App.jsx": (
            "import { useState } from 'react'\n\n"
            "export default function App() {\n"
            "  const [count, setCount] = useState(0)\n"
            "  return (\n"
            '    <main className="app">\n'
            f"      <h1>{'{'}'{js_title}'{'}'}</h1>\n"
            "      <p>A runnable Vite + React starter generated offline by SkyN3t.</p>\n"
            '      <button onClick={() => setCount((c) => c + 1)}>\n'
            "        count is {count}\n"
            "      </button>\n"
            "    </main>\n"
            "  )\n"
            "}\n"
        ),
        "src/styles.css": (
            ":root { font-family: system-ui, sans-serif; }\n"
            "body { margin: 0; display: grid; place-items: center; min-height: 100vh; }\n"
            ".app { text-align: center; padding: 2rem; }\n"
            "button { font-size: 1rem; padding: 0.5rem 1rem; cursor: pointer; }\n"
        ),
        ".gitignore": "node_modules\ndist\n",
        "README.md": compose_readme(
            title,
            brief,
            stack_label="Vite + React",
            install="```bash\nnpm install\n```\n\nRequires Node.js 18+.",
            usage=(
                "Start the dev server with hot-reload:\n\n"
                "```bash\nnpm run dev\n```\n\n"
                "Build a production bundle and preview it:\n\n"
                "```bash\nnpm run build\nnpm run preview\n```"
            ),
            structure=[
                ("index.html", "HTML entry that mounts the React app"),
                ("src/main.jsx", "React bootstrap — renders <App /> into #root"),
                ("src/App.jsx", "Root component (extend this with your UI)"),
                ("src/styles.css", "Global styles"),
                ("vite.config.js", "Vite + React plugin configuration"),
                ("package.json", "Dependencies and npm scripts"),
            ],
            features=[
                "Vite dev server with instant hot-module reload",
                "React 18 component architecture",
                "Production build + preview scripts",
            ],
        ),
    }


def _static_html(app_name: str, brief: str) -> dict[str, str]:
    title = brief.strip() or app_name
    # Escape for HTML so a brief with <, >, & doesn't emit stray/unclosed tags.
    html_title = title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return {
        "index.html": (
            "<!doctype html>\n"
            '<html lang="en">\n'
            "  <head>\n"
            '    <meta charset="UTF-8" />\n'
            '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
            f"    <title>{html_title}</title>\n"
            '    <link rel="stylesheet" href="styles.css" />\n'
            "  </head>\n"
            "  <body>\n"
            f"    <main><h1>{html_title}</h1>\n"
            "    <p>A runnable static site generated offline by SkyN3t.</p>\n"
            '    <button id="cta">Click me</button></main>\n'
            '    <script src="main.js"></script>\n'
            "  </body>\n"
            "</html>\n"
        ),
        "styles.css": (
            "body { font-family: system-ui, sans-serif; display: grid;"
            " place-items: center; min-height: 100vh; margin: 0; }\n"
            "main { text-align: center; }\n"
        ),
        "main.js": (
            "let count = 0;\n"
            "const btn = document.getElementById('cta');\n"
            "btn.addEventListener('click', () => {\n"
            "  count += 1;\n"
            "  btn.textContent = `Clicked ${count} times`;\n"
            "});\n"
        ),
        "package.json": (
            "{\n"
            f'  "name": "{app_name}",\n'
            '  "private": true,\n'
            '  "version": "0.1.0",\n'
            f'  "description": "{_json_escape(title)}",\n'
            '  "scripts": {\n'
            '    "start": "npx serve .",\n'
            '    "dev": "npx serve ."\n'
            "  },\n"
            '  "dependencies": {},\n'
            '  "devDependencies": {\n'
            '    "serve": "^14.2.1"\n'
            "  }\n"
            "}\n"
        ),
        "README.md": compose_readme(
            title,
            brief,
            stack_label="static HTML + CSS + JavaScript",
            install=(
                "No build step. Either open `index.html` directly, or for a local "
                "server (recommended for correct paths):\n\n"
                "```bash\nnpm install\n```"
            ),
            usage=(
                "Open the site in a browser by double-clicking `index.html`, or "
                "serve it locally:\n\n"
                "```bash\nnpm start\n```\n\n"
                "Then visit the printed `http://localhost` URL."
            ),
            structure=[
                ("index.html", "Page markup and entry point"),
                ("styles.css", "Stylesheet"),
                ("main.js", "Client-side behavior"),
                ("package.json", "Optional local-server tooling"),
            ],
            features=[
                "Zero build step — pure HTML, CSS, and JS",
                "Loads instantly in any modern browser",
                "Optional local static server via npm",
            ],
        ),
    }


def _python_cli(app_name: str, brief: str) -> dict[str, str]:
    pkg = (app_name.replace("-", "_").strip() or "app")
    # a valid python identifier for the package dir
    if not pkg[0].isalpha() and pkg[0] != "_":
        pkg = f"app_{pkg}"
    title = brief.strip() or app_name
    return {
        "pyproject.toml": (
            "[project]\n"
            f'name = "{app_name}"\n'
            'version = "0.1.0"\n'
            f'description = "{_toml_escape(title)}"\n'
            'requires-python = ">=3.10"\n'
            "# Runtime dependencies. The stdlib (argparse) covers the starter; add\n"
            "# real packages here as the tool grows.\n"
            "dependencies = []\n\n"
            "[project.optional-dependencies]\n"
            '# `pip install -e ".[dev]"` to get the test/lint toolchain.\n'
            'dev = ["pytest>=7", "ruff>=0.1"]\n\n'
            "[project.scripts]\n"
            f'{app_name} = "{pkg}.cli:main"\n\n'
            "[build-system]\n"
            'requires = ["setuptools>=61"]\n'
            'build-backend = "setuptools.build_meta"\n'
        ),
        "requirements.txt": (
            "# Runtime dependencies for "
            f"{title}.\n"
            "# The starter relies only on the Python standard library; pin real\n"
            "# packages below as you add them (one per line).\n"
        ),
        "main.py": (
            '"""Root entrypoint: ``python main.py`` runs the CLI."""\n'
            "from __future__ import annotations\n\n"
            f"from {pkg}.cli import main\n\n\n"
            'if __name__ == "__main__":\n'
            "    raise SystemExit(main())\n"
        ),
        f"{pkg}/__init__.py": (
            f'"""{title} — generated offline by SkyN3t."""\n\n'
            '__version__ = "0.1.0"\n'
        ),
        f"{pkg}/core.py": (
            '"""Core logic for the tool (pure, easily testable)."""\n'
            "from __future__ import annotations\n\n\n"
            "def greet(name: str) -> str:\n"
            '    """Return a friendly greeting."""\n'
            "    name = (name or \"world\").strip() or \"world\"\n"
            '    return f"Hello, {name}!"\n'
        ),
        f"{pkg}/cli.py": (
            '"""Command-line interface."""\n'
            "from __future__ import annotations\n\n"
            "import argparse\n\n"
            f"from {pkg}.core import greet\n\n\n"
            "def build_parser() -> argparse.ArgumentParser:\n"
            f'    parser = argparse.ArgumentParser(prog="{app_name}", description="{title}")\n'
            '    parser.add_argument("--name", default="world", help="who to greet")\n'
            "    return parser\n\n\n"
            "def main(argv: list[str] | None = None) -> int:\n"
            "    args = build_parser().parse_args(argv)\n"
            "    print(greet(args.name))\n"
            "    return 0\n\n\n"
            'if __name__ == "__main__":\n'
            "    raise SystemExit(main())\n"
        ),
        "tests/test_core.py": (
            f"from {pkg}.core import greet\n\n\n"
            "def test_greet_default():\n"
            '    assert greet("world") == "Hello, world!"\n\n\n'
            "def test_greet_strips():\n"
            '    assert greet("  ada ") == "Hello, ada!"\n'
        ),
        "README.md": compose_readme(
            title,
            brief,
            stack_label="Python CLI",
            install=(
                "Requires Python 3.10+. Install in a virtual environment:\n\n"
                "```bash\n"
                "python -m venv .venv\n"
                "source .venv/bin/activate   # Windows: .venv\\Scripts\\activate\n"
                'pip install -e ".[dev]"\n'
                "```"
            ),
            usage=(
                "Run directly:\n\n"
                "```bash\npython main.py --name you\n```\n\n"
                f"Or, once installed, via the `{app_name}` console script:\n\n"
                f"```bash\n{app_name} --name you\n```\n\n"
                "Use `--help` to list all options."
            ),
            structure=[
                ("main.py", "Root entrypoint — `python main.py` runs the CLI"),
                (f"{pkg}/cli.py", "Argument parsing and command dispatch"),
                (f"{pkg}/core.py", "Pure, testable core logic"),
                (f"{pkg}/__init__.py", "Package metadata"),
                ("tests/test_core.py", "Unit tests for the core logic"),
                ("pyproject.toml", "Build config, console script, and dependencies"),
            ],
            features=[
                "Argparse-based command-line interface",
                "Separated pure core logic for easy testing",
                "Installable console script entry point",
            ],
            extra=(
                "### Tests\n\n"
                "```bash\npytest\n```"
            ),
        ),
        ".gitignore": "__pycache__/\n*.pyc\n.venv/\ndist/\n*.egg-info/\n",
    }


def _fastapi(app_name: str, brief: str) -> dict[str, str]:
    title = brief.strip() or app_name
    return {
        "main.py": (
            '"""' + f"{title} — a runnable FastAPI app generated offline by SkyN3t." + '"""\n\n'
            "from __future__ import annotations\n\n"
            "from fastapi import FastAPI\n\n"
            'app = FastAPI(title="' + title + '")\n\n\n'
            '@app.get("/")\n'
            "async def root() -> dict[str, str]:\n"
            '    return {"message": "' + title + ' is running"}\n\n\n'
            '@app.get("/health")\n'
            "async def health() -> dict[str, str]:\n"
            '    return {"status": "ok"}\n'
        ),
        "test_main.py": (
            "from fastapi.testclient import TestClient\n\n"
            "from main import app\n\n"
            "client = TestClient(app)\n\n\n"
            "def test_health():\n"
            '    resp = client.get("/health")\n'
            "    assert resp.status_code == 200\n"
            '    assert resp.json()["status"] == "ok"\n'
        ),
        "requirements.txt": (
            f"# Runtime + test dependencies for {title}.\n"
            "fastapi>=0.110        # web framework\n"
            "uvicorn[standard]>=0.27  # ASGI server (run with `uvicorn main:app`)\n"
            "httpx>=0.27           # used by fastapi.testclient for the test suite\n"
        ),
        "README.md": compose_readme(
            title,
            brief,
            stack_label="FastAPI",
            install=(
                "Requires Python 3.10+. Install dependencies into a virtual env:\n\n"
                "```bash\n"
                "python -m venv .venv\n"
                "source .venv/bin/activate   # Windows: .venv\\Scripts\\activate\n"
                "pip install -r requirements.txt\n"
                "```"
            ),
            usage=(
                "Run the development server with auto-reload:\n\n"
                "```bash\nuvicorn main:app --reload\n```\n\n"
                "The API is then available at `http://127.0.0.1:8000`:\n\n"
                "- `GET /` — service status\n"
                "- `GET /health` — health check\n"
                "- `GET /docs` — interactive OpenAPI docs (Swagger UI)"
            ),
            structure=[
                ("main.py", "FastAPI application and route handlers"),
                ("test_main.py", "API tests via fastapi.testclient"),
                ("requirements.txt", "Runtime and test dependencies"),
            ],
            features=[
                "FastAPI app with health and root endpoints",
                "Auto-generated OpenAPI / Swagger docs at /docs",
                "Test suite using the built-in TestClient",
            ],
            extra=(
                "### Tests\n\n"
                "```bash\npytest\n```"
            ),
        ),
    }


def _node_express(app_name: str, brief: str) -> dict[str, str]:
    title = brief.strip() or app_name
    return {
        "package.json": (
            "{\n"
            f'  "name": "{app_name}",\n'
            '  "version": "0.1.0",\n'
            f'  "description": "{_json_escape(title)}",\n'
            '  "type": "commonjs",\n'
            '  "main": "server.js",\n'
            '  "scripts": {\n'
            '    "start": "node server.js",\n'
            '    "test": "node test.js"\n'
            "  },\n"
            '  "dependencies": { "express": "^4.18.2" }\n'
            "}\n"
        ),
        "server.js": (
            "const express = require('express');\n"
            "const app = express();\n"
            "const port = process.env.PORT || 3000;\n\n"
            "app.get('/', (req, res) => res.json({ message: '" + title + " is running' }));\n"
            "app.get('/health', (req, res) => res.json({ status: 'ok' }));\n\n"
            "if (require.main === module) {\n"
            "  app.listen(port, () => console.log(`listening on ${port}`));\n"
            "}\n"
            "module.exports = app;\n"
        ),
        "test.js": (
            "const assert = require('assert');\n"
            "const app = require('./server.js');\n\n"
            "assert.strictEqual(typeof app, 'function', 'server.js must export the express app');\n"
            "console.log('ok');\n"
        ),
        ".gitignore": "node_modules\n",
        "README.md": compose_readme(
            title,
            brief,
            stack_label="Node.js + Express",
            install="```bash\nnpm install\n```\n\nRequires Node.js 18+.",
            usage=(
                "Start the server:\n\n"
                "```bash\nnpm start\n```\n\n"
                "It listens on `http://localhost:3000` (override with the `PORT` "
                "environment variable):\n\n"
                "- `GET /` — service status\n"
                "- `GET /health` — health check"
            ),
            structure=[
                ("server.js", "Express app, routes, and server bootstrap"),
                ("test.js", "Smoke test asserting the app exports correctly"),
                ("package.json", "Dependencies and npm scripts"),
            ],
            features=[
                "Express HTTP server with health and root routes",
                "Configurable port via the PORT env var",
                "Exports the app for testing/embedding",
            ],
            extra=(
                "### Tests\n\n"
                "```bash\nnpm test\n```"
            ),
        ),
    }


def _react_native_expo(app_name: str, brief: str) -> dict[str, str]:
    """A genuinely runnable minimal Expo (React Native + TypeScript) app.

    Mobile can't be iframe-previewed like the web stacks, so the proof for this
    stack is a type-check (``npm run typecheck`` -> ``tsc --noEmit``) rather than
    a dev server. The app ships a real default-exported root screen with a
    reusable component and local state, plus a test, so ``delivered != empty``.
    """
    title = brief.strip() or app_name
    # A JSON-safe display title (for app.json) and a JS-string-literal title (for
    # the JSX), plus a slug for the Expo config.
    # Strip newlines too (a brief from a web-form textarea can contain them) —
    # otherwise app.json becomes invalid JSON and App.tsx an unterminated string.
    safe_title = title.replace('"', "'").replace("\n", " ").replace("\r", " ")
    js_title = (
        title.replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ").replace("\r", " ")
    )
    slug = _re.sub(r"[^a-z0-9-]+", "-", app_name.lower()).strip("-") or "app"
    return {
        "package.json": (
            "{\n"
            f'  "name": "{slug}",\n'
            '  "version": "0.1.0",\n'
            '  "private": true,\n'
            '  "main": "node_modules/expo/AppEntry.js",\n'
            '  "scripts": {\n'
            '    "start": "expo start",\n'
            '    "android": "expo start --android",\n'
            '    "ios": "expo start --ios",\n'
            '    "typecheck": "tsc --noEmit"\n'
            "  },\n"
            '  "dependencies": {\n'
            '    "expo": "~51.0.0",\n'
            '    "expo-status-bar": "~1.12.1",\n'
            '    "react": "18.2.0",\n'
            '    "react-native": "0.74.5"\n'
            "  },\n"
            '  "devDependencies": {\n'
            '    "@types/react": "~18.2.45",\n'
            '    "typescript": "~5.3.3"\n'
            "  }\n"
            "}\n"
        ),
        "app.json": (
            "{\n"
            '  "expo": {\n'
            f'    "name": "{safe_title}",\n'
            f'    "slug": "{slug}",\n'
            '    "version": "1.0.0",\n'
            '    "orientation": "portrait",\n'
            '    "userInterfaceStyle": "light",\n'
            '    "splash": {\n'
            '      "resizeMode": "contain",\n'
            '      "backgroundColor": "#ffffff"\n'
            "    },\n"
            '    "ios": { "supportsTablet": true },\n'
            '    "android": {},\n'
            '    "web": { "bundler": "metro" }\n'
            "  }\n"
            "}\n"
        ),
        "tsconfig.json": (
            "{\n"
            '  "extends": "expo/tsconfig.base",\n'
            '  "compilerOptions": {\n'
            '    "strict": true,\n'
            '    "jsx": "react-native",\n'
            '    "esModuleInterop": true,\n'
            '    "skipLibCheck": true\n'
            "  },\n"
            '  "exclude": ["node_modules"]\n'
            "}\n"
        ),
        "babel.config.js": (
            "module.exports = function (api) {\n"
            "  api.cache(true);\n"
            "  return {\n"
            "    presets: ['babel-preset-expo'],\n"
            "  };\n"
            "};\n"
        ),
        "App.tsx": (
            "import { useState } from 'react';\n"
            "import { StatusBar } from 'expo-status-bar';\n"
            "import { StyleSheet, Text, View } from 'react-native';\n\n"
            "import { Counter } from './src/components/Counter';\n\n"
            "export default function App(): JSX.Element {\n"
            "  const [taps, setTaps] = useState(0);\n"
            "  return (\n"
            "    <View style={styles.container}>\n"
            "      <Text style={styles.title}>{'" + js_title + "'}</Text>\n"
            "      <Text style={styles.subtitle}>\n"
            "        A runnable Expo app generated offline by SkyN3t.\n"
            "      </Text>\n"
            "      <Counter value={taps} onPress={() => setTaps((n) => n + 1)} />\n"
            "      <StatusBar style=\"auto\" />\n"
            "    </View>\n"
            "  );\n"
            "}\n\n"
            "const styles = StyleSheet.create({\n"
            "  container: {\n"
            "    flex: 1,\n"
            "    backgroundColor: '#fff',\n"
            "    alignItems: 'center',\n"
            "    justifyContent: 'center',\n"
            "    padding: 24,\n"
            "  },\n"
            "  title: { fontSize: 24, fontWeight: '600', marginBottom: 8 },\n"
            "  subtitle: { fontSize: 14, color: '#555', textAlign: 'center', marginBottom: 24 },\n"
            "});\n"
        ),
        "src/components/Counter.tsx": (
            "import { Pressable, StyleSheet, Text } from 'react-native';\n\n"
            "export interface CounterProps {\n"
            "  value: number;\n"
            "  onPress: () => void;\n"
            "}\n\n"
            "export function Counter({ value, onPress }: CounterProps): JSX.Element {\n"
            "  return (\n"
            "    <Pressable accessibilityRole=\"button\" style={styles.button} onPress={onPress}>\n"
            "      <Text style={styles.label}>Tapped {value} times</Text>\n"
            "    </Pressable>\n"
            "  );\n"
            "}\n\n"
            "const styles = StyleSheet.create({\n"
            "  button: {\n"
            "    backgroundColor: '#1f6feb',\n"
            "    paddingHorizontal: 20,\n"
            "    paddingVertical: 12,\n"
            "    borderRadius: 8,\n"
            "  },\n"
            "  label: { color: '#fff', fontSize: 16 },\n"
            "});\n"
        ),
        ".gitignore": "node_modules/\n.expo/\ndist/\nweb-build/\n*.log\n",
        "README.md": compose_readme(
            title,
            brief,
            stack_label="Expo + React Native + TypeScript",
            install=(
                "```bash\nnpm install\n```\n\n"
                "Requires Node.js 18+ and the Expo CLI (`npx expo`)."
            ),
            usage=(
                "Start the app (opens the Expo dev tools):\n\n"
                "```bash\nnpm start\n```\n\n"
                "Then press `i` for the iOS simulator, `a` for Android, or scan the QR "
                "code with the Expo Go app on your phone. Type-check the app:\n\n"
                "```bash\nnpm run typecheck\n```"
            ),
            structure=[
                ("App.tsx", "Root screen — default-exported <App />, wires the UI together"),
                ("src/components/Counter.tsx", "Reusable component with typed props + local state"),
                ("app.json", "Expo app config (name, slug, platforms)"),
                ("package.json", "Dependencies and npm scripts (start, ios, android, typecheck)"),
                ("tsconfig.json", "TypeScript config (extends expo/tsconfig.base)"),
                ("babel.config.js", "Babel preset for Expo"),
            ],
            features=[
                "Cross-platform iOS + Android from one codebase via Expo",
                "TypeScript with a reusable, typed component",
                "Local state with React hooks",
                "Type-checked (tsc --noEmit) instead of a web dev-server preview",
            ],
            extra=(
                "> **Note:** mobile apps run on a device/simulator and cannot be "
                "previewed in an iframe like the web stacks. The proof for this stack "
                "is a type check (`npm run typecheck`), not a dev-server boot."
            ),
        ),
    }


def _nextjs(app_name: str, brief: str) -> dict[str, str]:
    """A genuinely runnable minimal Next.js (App Router) app in plain JSX.

    Plain JSX (no TypeScript) keeps the offline scaffold buildable with
    ``next build`` without dragging in a TS toolchain / @types. Ships a real
    default-exported page reflecting the brief, a root layout, the config, and a
    README.
    """
    title = brief.strip() or app_name
    js_title = title.replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ").replace("\r", " ")
    return {
        "package.json": (
            "{\n"
            f'  "name": "{app_name}",\n'
            '  "private": true,\n'
            '  "version": "0.1.0",\n'
            f'  "description": "{_json_escape(title)}",\n'
            '  "scripts": {\n'
            '    "dev": "next dev",\n'
            '    "build": "next build",\n'
            '    "start": "next start"\n'
            "  },\n"
            '  "dependencies": {\n'
            '    "next": "^14.2.0",\n'
            '    "react": "^18.2.0",\n'
            '    "react-dom": "^18.2.0"\n'
            "  }\n"
            "}\n"
        ),
        "next.config.js": (
            "/** @type {import('next').NextConfig} */\n"
            "const nextConfig = {\n"
            "  reactStrictMode: true,\n"
            "};\n\n"
            "module.exports = nextConfig;\n"
        ),
        "jsconfig.json": (
            "{\n"
            '  "compilerOptions": {\n'
            '    "baseUrl": "."\n'
            "  }\n"
            "}\n"
        ),
        "app/layout.jsx": (
            "import './globals.css';\n\n"
            "export const metadata = {\n"
            f"  title: '{js_title}',\n"
            "  description: 'Generated offline by SkyN3t.',\n"
            "};\n\n"
            "export default function RootLayout({ children }) {\n"
            "  return (\n"
            '    <html lang="en">\n'
            "      <body>{children}</body>\n"
            "    </html>\n"
            "  );\n"
            "}\n"
        ),
        "app/page.jsx": (
            "'use client';\n\n"
            "import { useState } from 'react';\n\n"
            "export default function Home() {\n"
            "  const [count, setCount] = useState(0);\n"
            "  return (\n"
            '    <main className="app">\n'
            f"      <h1>{'{'}'{js_title}'{'}'}</h1>\n"
            "      <p>A runnable Next.js (App Router) starter generated offline by SkyN3t.</p>\n"
            "      <button onClick={() => setCount((c) => c + 1)}>count is {count}</button>\n"
            "    </main>\n"
            "  );\n"
            "}\n"
        ),
        "app/globals.css": (
            ":root { font-family: system-ui, sans-serif; }\n"
            "body { margin: 0; display: grid; place-items: center; min-height: 100vh; }\n"
            ".app { text-align: center; padding: 2rem; }\n"
            "button { font-size: 1rem; padding: 0.5rem 1rem; cursor: pointer; }\n"
        ),
        ".gitignore": "node_modules\n.next\nout\n",
        "README.md": compose_readme(
            title,
            brief,
            stack_label="Next.js (App Router)",
            install="```bash\nnpm install\n```\n\nRequires Node.js 18.18+.",
            usage=(
                "Start the dev server with hot-reload:\n\n"
                "```bash\nnpm run dev\n```\n\n"
                "Then open `http://localhost:3000`. Build for production and serve it:\n\n"
                "```bash\nnpm run build\nnpm start\n```"
            ),
            structure=[
                ("app/page.jsx", "Home page — default-exported route component"),
                ("app/layout.jsx", "Root layout wrapping every page (<html>/<body>)"),
                ("app/globals.css", "Global styles imported by the layout"),
                ("next.config.js", "Next.js configuration"),
                ("package.json", "Dependencies and npm scripts (dev/build/start)"),
            ],
            features=[
                "Next.js App Router with a default-exported page + root layout",
                "React 18 client component with local state",
                "Production build + start scripts (next build / next start)",
            ],
        ),
    }


def _astro(app_name: str, brief: str) -> dict[str, str]:
    """A genuinely runnable minimal Astro site — buildable with ``astro build``.

    Ships a real index page (with Astro frontmatter), a reusable layout, the
    config, and a README. Astro renders to static HTML by default, so the page
    content reflects the brief.
    """
    title = brief.strip() or app_name
    # Astro frontmatter is JS; single-quote-escape the title for the template.
    js_title = title.replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ").replace("\r", " ")
    # The HTML body interpolates {title}; angle brackets in the brief would break
    # markup, so neutralise them for the visible heading.
    html_title = js_title.replace("<", "&lt;").replace(">", "&gt;")
    return {
        "package.json": (
            "{\n"
            f'  "name": "{app_name}",\n'
            '  "private": true,\n'
            '  "version": "0.1.0",\n'
            f'  "description": "{_json_escape(title)}",\n'
            '  "type": "module",\n'
            '  "scripts": {\n'
            '    "dev": "astro dev",\n'
            '    "build": "astro build",\n'
            '    "preview": "astro preview"\n'
            "  },\n"
            '  "dependencies": {\n'
            '    "astro": "^4.10.0"\n'
            "  }\n"
            "}\n"
        ),
        "astro.config.mjs": (
            "import { defineConfig } from 'astro/config';\n\n"
            "// https://astro.build/config\n"
            "export default defineConfig({});\n"
        ),
        "src/layouts/Layout.astro": (
            "---\n"
            "const { title } = Astro.props;\n"
            "---\n"
            "<!doctype html>\n"
            '<html lang="en">\n'
            "  <head>\n"
            '    <meta charset="utf-8" />\n'
            '    <meta name="viewport" content="width=device-width, initial-scale=1" />\n'
            "    <title>{title}</title>\n"
            "  </head>\n"
            "  <body>\n"
            "    <slot />\n"
            "  </body>\n"
            "</html>\n"
        ),
        "src/pages/index.astro": (
            "---\n"
            "import Layout from '../layouts/Layout.astro';\n"
            f"const title = '{js_title}';\n"
            "---\n"
            "<Layout title={title}>\n"
            "  <main>\n"
            f"    <h1>{html_title}</h1>\n"
            "    <p>A runnable Astro site generated offline by SkyN3t.</p>\n"
            "  </main>\n"
            "</Layout>\n\n"
            "<style>\n"
            "  main { font-family: system-ui, sans-serif; text-align: center; padding: 2rem; }\n"
            "</style>\n"
        ),
        ".gitignore": "node_modules\ndist\n.astro\n",
        "README.md": compose_readme(
            title,
            brief,
            stack_label="Astro",
            install="```bash\nnpm install\n```\n\nRequires Node.js 18.14+.",
            usage=(
                "Start the dev server with hot-reload:\n\n"
                "```bash\nnpm run dev\n```\n\n"
                "Then open `http://localhost:4321`. Build the static site and preview it:\n\n"
                "```bash\nnpm run build\nnpm run preview\n```"
            ),
            structure=[
                ("src/pages/index.astro", "Home page — Astro routes from src/pages/"),
                ("src/layouts/Layout.astro", "Shared HTML document layout"),
                ("astro.config.mjs", "Astro configuration"),
                ("package.json", "Dependencies and npm scripts (dev/build/preview)"),
            ],
            features=[
                "Astro file-based routing (pages live in src/pages/)",
                "Reusable .astro layout with a typed prop",
                "Static build output via `astro build`",
            ],
        ),
    }


def _remix(app_name: str, brief: str) -> dict[str, str]:
    """A genuinely runnable minimal Remix (Vite) app — buildable with the Remix
    Vite build (``remix vite:build``).

    Ships the root document (``app/root.tsx``), the index route, the Vite config
    wiring the Remix plugin, a tsconfig, and a README. TypeScript here mirrors the
    real Remix template (which is TS-first); the build type-checks via Remix's
    bundler, not a standalone ``tsc``.
    """
    title = brief.strip() or app_name
    js_title = title.replace("\\", "\\\\").replace("`", "\\`").replace("$", "\\$").replace("\n", " ").replace("\r", " ")
    return {
        "package.json": (
            "{\n"
            f'  "name": "{app_name}",\n'
            '  "private": true,\n'
            '  "version": "0.1.0",\n'
            f'  "description": "{_json_escape(title)}",\n'
            '  "type": "module",\n'
            '  "sideEffects": false,\n'
            '  "scripts": {\n'
            '    "dev": "remix vite:dev",\n'
            '    "build": "remix vite:build",\n'
            '    "start": "remix-serve ./build/server/index.js"\n'
            "  },\n"
            '  "dependencies": {\n'
            '    "@remix-run/node": "^2.10.0",\n'
            '    "@remix-run/react": "^2.10.0",\n'
            '    "@remix-run/serve": "^2.10.0",\n'
            '    "isbot": "^4.1.0",\n'
            '    "react": "^18.2.0",\n'
            '    "react-dom": "^18.2.0"\n'
            "  },\n"
            '  "devDependencies": {\n'
            '    "@remix-run/dev": "^2.10.0",\n'
            '    "@types/react": "^18.2.0",\n'
            '    "@types/react-dom": "^18.2.0",\n'
            '    "typescript": "^5.4.0",\n'
            '    "vite": "^5.2.0",\n'
            '    "vite-tsconfig-paths": "^4.3.0"\n'
            "  },\n"
            '  "engines": { "node": ">=18.0.0" }\n'
            "}\n"
        ),
        "vite.config.ts": (
            "import { vitePlugin as remix } from '@remix-run/dev';\n"
            "import { defineConfig } from 'vite';\n"
            "import tsconfigPaths from 'vite-tsconfig-paths';\n\n"
            "export default defineConfig({\n"
            "  plugins: [remix(), tsconfigPaths()],\n"
            "});\n"
        ),
        "tsconfig.json": (
            "{\n"
            '  "include": ["**/*.ts", "**/*.tsx"],\n'
            '  "compilerOptions": {\n'
            '    "lib": ["DOM", "DOM.Iterable", "ES2022"],\n'
            '    "types": ["@remix-run/node", "vite/client"],\n'
            '    "isolatedModules": true,\n'
            '    "esModuleInterop": true,\n'
            '    "jsx": "react-jsx",\n'
            '    "module": "ESNext",\n'
            '    "moduleResolution": "Bundler",\n'
            '    "resolveJsonModule": true,\n'
            '    "target": "ES2022",\n'
            '    "strict": true,\n'
            '    "skipLibCheck": true,\n'
            '    "baseUrl": ".",\n'
            '    "noEmit": true\n'
            "  }\n"
            "}\n"
        ),
        "app/root.tsx": (
            "import {\n"
            "  Links,\n"
            "  Meta,\n"
            "  Outlet,\n"
            "  Scripts,\n"
            "  ScrollRestoration,\n"
            "} from '@remix-run/react';\n\n"
            "export default function App() {\n"
            "  return (\n"
            '    <html lang="en">\n'
            "      <head>\n"
            '        <meta charSet="utf-8" />\n'
            '        <meta name="viewport" content="width=device-width, initial-scale=1" />\n'
            "        <Meta />\n"
            "        <Links />\n"
            "      </head>\n"
            "      <body>\n"
            "        <Outlet />\n"
            "        <ScrollRestoration />\n"
            "        <Scripts />\n"
            "      </body>\n"
            "    </html>\n"
            "  );\n"
            "}\n"
        ),
        "app/routes/_index.tsx": (
            "import type { MetaFunction } from '@remix-run/node';\n\n"
            "export const meta: MetaFunction = () => {\n"
            f"  return [{{ title: `{js_title}` }}];\n"
            "};\n\n"
            "export default function Index() {\n"
            "  return (\n"
            "    <main style={{ fontFamily: 'system-ui, sans-serif', textAlign: 'center', padding: '2rem' }}>\n"
            f"      <h1>{'{'}`{js_title}`{'}'}</h1>\n"
            "      <p>A runnable Remix app generated offline by SkyN3t.</p>\n"
            "    </main>\n"
            "  );\n"
            "}\n"
        ),
        ".gitignore": "node_modules\n/build\n/.cache\n",
        "README.md": compose_readme(
            title,
            brief,
            stack_label="Remix (Vite)",
            install="```bash\nnpm install\n```\n\nRequires Node.js 18+.",
            usage=(
                "Start the dev server:\n\n"
                "```bash\nnpm run dev\n```\n\n"
                "Then open `http://localhost:3000`. Build for production and serve it:\n\n"
                "```bash\nnpm run build\nnpm start\n```"
            ),
            structure=[
                ("app/root.tsx", "Root document — the <html> shell and <Outlet />"),
                ("app/routes/_index.tsx", "Index route ('/') — default-exported component"),
                ("vite.config.ts", "Vite config wiring the Remix plugin"),
                ("tsconfig.json", "TypeScript configuration"),
                ("package.json", "Dependencies and npm scripts (dev/build/start)"),
            ],
            features=[
                "Remix file-based routing with a typed meta() export",
                "Root document + nested route via <Outlet />",
                "Vite-powered dev server and production build",
            ],
        ),
    }


def _react_vite_threejs(app_name: str, brief: str) -> dict[str, str]:
    """The react_vite scaffold with a Three.js rotating-cube scene.

    Reuses the base Vite + React scaffold (config, index.html, README) and swaps
    the starter ``App.jsx`` for a real Three.js scene plus the ``three`` dep. Only
    invoked when the brief implies 3D (see :func:`_implies_3d`).
    """
    title = brief.strip() or app_name
    files = _react_vite(app_name, brief)
    # Add `three` to the dependencies block of the existing package.json.
    files["package.json"] = files["package.json"].replace(
        '    "react-dom": "^18.2.0"\n',
        '    "react-dom": "^18.2.0",\n    "three": "^0.165.0"\n',
    )
    files["src/App.jsx"] = (
        "import { useEffect, useRef } from 'react'\n"
        "import * as THREE from 'three'\n\n"
        "export default function App() {\n"
        "  const mountRef = useRef(null)\n\n"
        "  useEffect(() => {\n"
        "    const mount = mountRef.current\n"
        "    if (!mount) return\n"
        "    const width = mount.clientWidth || window.innerWidth\n"
        "    const height = mount.clientHeight || window.innerHeight\n\n"
        "    const scene = new THREE.Scene()\n"
        "    const camera = new THREE.PerspectiveCamera(70, width / height, 0.1, 100)\n"
        "    camera.position.z = 3\n\n"
        "    const renderer = new THREE.WebGLRenderer({ antialias: true })\n"
        "    renderer.setSize(width, height)\n"
        "    mount.appendChild(renderer.domElement)\n\n"
        "    const geometry = new THREE.BoxGeometry()\n"
        "    const material = new THREE.MeshNormalMaterial()\n"
        "    const cube = new THREE.Mesh(geometry, material)\n"
        "    scene.add(cube)\n\n"
        "    let frame\n"
        "    const animate = () => {\n"
        "      cube.rotation.x += 0.01\n"
        "      cube.rotation.y += 0.01\n"
        "      renderer.render(scene, camera)\n"
        "      frame = requestAnimationFrame(animate)\n"
        "    }\n"
        "    animate()\n\n"
        "    return () => {\n"
        "      cancelAnimationFrame(frame)\n"
        "      renderer.dispose()\n"
        "      mount.removeChild(renderer.domElement)\n"
        "    }\n"
        "  }, [])\n\n"
        "  return (\n"
        '    <main className="app">\n'
        f"      <h1>{title}</h1>\n"
        "      <p>A rotating cube rendered with Three.js — generated offline by SkyN3t.</p>\n"
        '      <div ref={mountRef} className="canvas-host" />\n'
        "    </main>\n"
        "  )\n"
        "}\n"
    )
    files["src/styles.css"] = (
        ":root { font-family: system-ui, sans-serif; }\n"
        "body { margin: 0; }\n"
        ".app { text-align: center; padding: 1rem; }\n"
        ".canvas-host { width: 100%; height: 70vh; }\n"
    )
    return files


def _static_threejs(app_name: str, brief: str) -> dict[str, str]:
    """The static_html scaffold with a Three.js rotating-cube scene.

    Reuses the base static scaffold (package.json, README) and swaps the page +
    script for a real Three.js scene loaded from a CDN module. Only invoked when
    the brief implies 3D (see :func:`_implies_3d`).
    """
    title = brief.strip() or app_name
    files = _static_html(app_name, brief)
    files["index.html"] = (
        "<!doctype html>\n"
        '<html lang="en">\n'
        "  <head>\n"
        '    <meta charset="UTF-8" />\n'
        '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
        f"    <title>{title}</title>\n"
        '    <link rel="stylesheet" href="styles.css" />\n'
        "  </head>\n"
        "  <body>\n"
        f"    <main><h1>{title}</h1>\n"
        "    <p>A rotating cube rendered with Three.js — generated offline by SkyN3t.</p></main>\n"
        '    <canvas id="scene"></canvas>\n'
        '    <script type="importmap">\n'
        '    { "imports": { "three": "https://unpkg.com/three@0.165.0/build/three.module.js" } }\n'
        "    </script>\n"
        '    <script type="module" src="main.js"></script>\n'
        "  </body>\n"
        "</html>\n"
    )
    files["styles.css"] = (
        "body { font-family: system-ui, sans-serif; margin: 0; }\n"
        "main { text-align: center; padding: 1rem; }\n"
        "#scene { display: block; width: 100%; height: 70vh; }\n"
    )
    files["main.js"] = (
        "import * as THREE from 'three';\n\n"
        "const canvas = document.getElementById('scene');\n"
        "const width = canvas.clientWidth || window.innerWidth;\n"
        "const height = canvas.clientHeight || window.innerHeight;\n\n"
        "const scene = new THREE.Scene();\n"
        "const camera = new THREE.PerspectiveCamera(70, width / height, 0.1, 100);\n"
        "camera.position.z = 3;\n\n"
        "const renderer = new THREE.WebGLRenderer({ canvas, antialias: true });\n"
        "renderer.setSize(width, height, false);\n\n"
        "const cube = new THREE.Mesh(new THREE.BoxGeometry(), new THREE.MeshNormalMaterial());\n"
        "scene.add(cube);\n\n"
        "function animate() {\n"
        "  cube.rotation.x += 0.01;\n"
        "  cube.rotation.y += 0.01;\n"
        "  renderer.render(scene, camera);\n"
        "  requestAnimationFrame(animate);\n"
        "}\n"
        "animate();\n"
    )
    return files


def _tauri(app_name: str, brief: str) -> dict[str, str]:
    """Cross-platform desktop (Tauri) scaffold = skyn3t's Vite/React frontend (codegen
    fills it with the app UI) + a minimal, FIXED src-tauri/ Rust shell for native file
    dialogs, fs access, and a run_command for scripting. `npm run build` builds the
    frontend (the proof); `npm run tauri build` produces the Mac .app / Windows .msi."""
    files = dict(_react_vite(app_name, brief))
    title = (brief.strip() or app_name).split("\n")[0][:80]
    crate = _re.sub(r"[^a-z0-9_]", "_", app_name.lower()).strip("_") or "app"
    ident = "com.greentext." + (_re.sub(r"[^a-z0-9]", "", app_name.lower()) or "app")
    prod = _re.sub(r"[^A-Za-z0-9 _-]", "", title) or app_name

    files["package.json"] = (
        "{\n"
        f'  "name": "{app_name}",\n'
        '  "private": true,\n'
        '  "version": "0.1.0",\n'
        '  "type": "module",\n'
        '  "scripts": {\n'
        '    "dev": "vite",\n'
        '    "build": "vite build",\n'
        '    "preview": "vite preview",\n'
        '    "tauri": "tauri"\n'
        "  },\n"
        '  "dependencies": {\n'
        '    "react": "^18.2.0",\n'
        '    "react-dom": "^18.2.0",\n'
        '    "@tauri-apps/api": "^1.6.0"\n'
        "  },\n"
        '  "devDependencies": {\n'
        '    "@vitejs/plugin-react": "^4.2.0",\n'
        '    "vite": "^5.0.0",\n'
        '    "@tauri-apps/cli": "^1.6.0"\n'
        "  }\n"
        "}\n"
    )
    files["vite.config.js"] = (
        "import { defineConfig } from 'vite'\n"
        "import react from '@vitejs/plugin-react'\n\n"
        "// Tauri wants a fixed dev port + no clearScreen so its CLI can attach.\n"
        "export default defineConfig({\n"
        "  plugins: [react()],\n"
        "  clearScreen: false,\n"
        "  server: { port: 1420, strictPort: true },\n"
        "})\n"
    )
    files["src-tauri/Cargo.toml"] = (
        "[package]\n"
        f'name = "{crate}"\n'
        'version = "0.1.0"\n'
        'edition = "2021"\n\n'
        "[build-dependencies]\n"
        'tauri-build = { version = "1.5", features = [] }\n\n'
        "[dependencies]\n"
        'tauri = { version = "1.6", features = ["dialog-open", "dialog-save", '
        '"fs-read-file", "fs-write-file", "fs-read-dir", "fs-exists", "fs-create-dir", '
        '"path-all", "shell-open", "os-all", "window-set-title"] }\n'
        'serde = { version = "1", features = ["derive"] }\n'
        'serde_json = "1"\n\n'
        "[features]\n"
        'custom-protocol = ["tauri/custom-protocol"]\n'
    )
    files["src-tauri/build.rs"] = "fn main() {\n    tauri_build::build()\n}\n"
    files["src-tauri/tauri.conf.json"] = (
        "{\n"
        '  "build": {\n'
        '    "beforeDevCommand": "npm run dev",\n'
        '    "beforeBuildCommand": "npm run build",\n'
        '    "devPath": "http://localhost:1420",\n'
        '    "distDir": "../dist"\n'
        "  },\n"
        f'  "package": {{ "productName": "{prod}", "version": "0.1.0" }},\n'
        '  "tauri": {\n'
        '    "allowlist": {\n'
        '      "dialog": { "all": true },\n'
        '      "fs": { "all": true, "scope": ["$HOME/**", "$DESKTOP/**", "$DOCUMENT/**", "$DOWNLOAD/**"] },\n'
        '      "shell": { "open": true },\n'
        '      "os": { "all": true },\n'
        '      "window": { "setTitle": true }\n'
        "    },\n"
        f'    "bundle": {{ "active": true, "identifier": "{ident}", "targets": "all" }},\n'
        f'    "windows": [{{ "title": "{prod}", "width": 1200, "height": 820, "resizable": true }}],\n'
        '    "security": { "csp": null }\n'
        "  }\n"
        "}\n"
    )
    files["src-tauri/src/main.rs"] = (
        '#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]\n\n'
        "use std::io::Write;\n"
        "use std::process::{Command, Stdio};\n\n"
        "// Run a shell command, piping `input` to stdin, returning stdout — powers\n"
        "// the editor's \"run command on selection\" / scripting for repeat work.\n"
        "#[tauri::command]\n"
        "fn run_command(command: String, input: String) -> Result<String, String> {\n"
        '    let shell = if cfg!(target_os = "windows") { "cmd" } else { "sh" };\n'
        '    let flag = if cfg!(target_os = "windows") { "/C" } else { "-c" };\n'
        "    let mut child = Command::new(shell)\n"
        "        .arg(flag).arg(&command)\n"
        "        .stdin(Stdio::piped()).stdout(Stdio::piped()).stderr(Stdio::piped())\n"
        "        .spawn().map_err(|e| e.to_string())?;\n"
        "    if let Some(mut stdin) = child.stdin.take() {\n"
        "        let _ = stdin.write_all(input.as_bytes());\n"
        "    }\n"
        "    let out = child.wait_with_output().map_err(|e| e.to_string())?;\n"
        "    if out.status.success() {\n"
        "        Ok(String::from_utf8_lossy(&out.stdout).into_owned())\n"
        "    } else {\n"
        "        Err(String::from_utf8_lossy(&out.stderr).into_owned())\n"
        "    }\n"
        "}\n\n"
        "fn main() {\n"
        "    tauri::Builder::default()\n"
        "        .invoke_handler(tauri::generate_handler![run_command])\n"
        "        .run(tauri::generate_context!())\n"
        '        .expect("error while running tauri application");\n'
        "}\n"
    )
    files["src-tauri/.gitignore"] = "/target\n"
    return files


def _phaser_main_js(art: bool) -> str:
    """The Phaser scene (``src/main.js``). With ``art`` it preloads role sprites and
    renders them with a colored-primitive FALLBACK (a missing/failed sprite never
    breaks the game); without it, the exact primitive-only baseline. The pure sim
    import + step() are identical either way — art is rendering-only."""
    preload = (
        (
            "  preload() {\n"
            "    // Role sprites written to public/assets/sprites/ at build time (generated\n"
            "    // by Replicate or a bundled CC0 fallback). If a file is absent Phaser skips\n"
            "    // it and create() falls back to a colored primitive — a missing sprite\n"
            "    // never breaks the game.\n"
            "    this.load.image('player', '/assets/sprites/player.png')\n"
            "    this.load.image('coin', '/assets/sprites/coin.png')\n"
            "  }\n\n"
        )
        if art
        else ""
    )
    views = (
        (
            "    this.playerView = this.textures.exists('player')\n"
            "      ? this.add.sprite(0, 0, 'player').setDisplaySize(40, 40)\n"
            "      : this.add.rectangle(0, 0, 36, 36, 0x4ade80)\n"
            "    this.coinView = this.textures.exists('coin')\n"
            "      ? this.add.sprite(0, 0, 'coin').setDisplaySize(28, 28)\n"
            "      : this.add.circle(0, 0, 12, 0xfbbf24)\n"
        )
        if art
        else (
            "    this.playerView = this.add.rectangle(0, 0, 36, 36, 0x4ade80)\n"
            "    this.coinView = this.add.circle(0, 0, 12, 0xfbbf24)\n"
        )
    )
    return (
        "import Phaser from 'phaser'\n"
        "import './styles.css'\n"
        "import { createState, step, isWin, isLose, WIDTH, HEIGHT } from './sim.js'\n\n"
        "// The Phaser scene owns NO game logic — all of it lives in the pure\n"
        "// src/sim.js (one authoritative state advanced by one step()). Each frame\n"
        "// the scene reads input, advances the sim by the real delta, and RENDERS\n"
        "// the returned state. This split is what lets the headless invariant gate\n"
        "// run the game's logic in Node.\n"
        "class MainScene extends Phaser.Scene {\n"
        "  constructor() { super('main') }\n\n"
        + preload +
        "  create() {\n"
        "    this.cameras.main.setBackgroundColor('#1d2330')\n"
        "    this.state = createState((Math.random() * 0xffffffff) >>> 0)\n\n"
        + views +
        "    this.hud = this.add.text(16, 16, '', {\n"
        "      fontFamily: 'system-ui, sans-serif', fontSize: '20px', color: '#e5e7eb',\n"
        "    })\n"
        "    this.add.text(16, HEIGHT - 30, 'Arrow keys or WASD to move · P to pause', {\n"
        "      fontFamily: 'system-ui, sans-serif', fontSize: '14px', color: '#94a3b8',\n"
        "    })\n\n"
        "    this.cursors = this.input.keyboard.createCursorKeys()\n"
        "    this.keys = this.input.keyboard.addKeys('W,A,S,D')\n"
        "    this.input.keyboard.on('keydown-P', () => { this.state.paused = !this.state.paused })\n"
        "  }\n\n"
        "  update(time, delta) {\n"
        "    const input = {\n"
        "      left: this.cursors.left.isDown || this.keys.A.isDown,\n"
        "      right: this.cursors.right.isDown || this.keys.D.isDown,\n"
        "      up: this.cursors.up.isDown || this.keys.W.isDown,\n"
        "      down: this.cursors.down.isDown || this.keys.S.isDown,\n"
        "      action: false,\n"
        "      pause: false,\n"
        "    }\n"
        "    // Advance the pure simulation by the real delta (seconds), then render.\n"
        "    this.state = step(this.state, input, delta / 1000)\n"
        "    this.draw(this.state)\n"
        "  }\n\n"
        "  draw(s) {\n"
        "    this.playerView.setPosition(s.player.x, s.player.y)\n"
        "    this.coinView.setPosition(s.coin.x, s.coin.y)\n"
        "    const status = isWin(s) ? '· YOU WIN' : isLose(s) ? '· TIME UP' : ''\n"
        "    this.hud.setText(`Score: ${s.score}  Time: ${Math.ceil(s.timeLeft)}  ${status}`)\n"
        "  }\n"
        "}\n\n"
        "const config = {\n"
        "  type: Phaser.AUTO,\n"
        "  parent: 'game-container',\n"
        "  width: WIDTH,\n"
        "  height: HEIGHT,\n"
        "  backgroundColor: '#1d2330',\n"
        "  scale: {\n"
        "    mode: Phaser.Scale.FIT,\n"
        "    autoCenter: Phaser.Scale.CENTER_BOTH,\n"
        "  },\n"
        "  scene: [MainScene],\n"
        "}\n\n"
        "// eslint-disable-next-line no-new\n"
        "new Phaser.Game(config)\n"
    )


def _phaser(app_name: str, brief: str, *, art: bool = False) -> dict[str, str]:
    """Phaser 3 + Vite 2D browser-game scaffold = a genuinely PLAYABLE vanilla-JS
    starter the codegen extends (NOT React — built fresh, not cloned from
    ``_react_vite``, so it never inherits react/react-dom/@vitejs-plugin-react).

    Architected as a **pure simulation core + a render-only scene** (the COIN
    REAPER fix): ALL game logic lives in ``src/sim.js`` — one authoritative state
    advanced by one ``step(state, input, dt)`` — with NO Phaser import. The Phaser
    scene in ``src/main.js`` owns no logic; each frame it reads input, calls
    ``step``, and RENDERS the returned state, so there is never a second copy of
    the simulation to desync from. Collision is a single distance test against the
    same coords that get drawn, so it can't fire "from far away". This split is
    also what makes the game testable by the headless invariant gate (it runs
    ``src/sim.js`` in Node). ``npm run build`` (``vite build`` → ``dist/``) is the
    build proof.
    """
    title = (brief.strip() or app_name).split("\n")[0][:120]
    html_title = title.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    return {
        "package.json": (
            "{\n"
            f'  "name": "{app_name}",\n'
            '  "private": true,\n'
            '  "version": "0.1.0",\n'
            f'  "description": "{_json_escape(title)}",\n'
            '  "type": "module",\n'
            '  "scripts": {\n'
            '    "dev": "vite",\n'
            '    "build": "vite build",\n'
            '    "preview": "vite preview"\n'
            "  },\n"
            '  "dependencies": {\n'
            '    "phaser": "^3.80.0"\n'
            "  },\n"
            '  "devDependencies": {\n'
            '    "vite": "^5.0.0"\n'
            "  }\n"
            "}\n"
        ),
        "vite.config.js": (
            "import { defineConfig } from 'vite'\n\n"
            "// A Phaser game is a plain-JS Vite app — no framework plugin needed.\n"
            "export default defineConfig({})\n"
        ),
        "index.html": (
            "<!doctype html>\n"
            '<html lang="en">\n'
            "  <head>\n"
            '    <meta charset="UTF-8" />\n'
            '    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n'
            f"    <title>{html_title}</title>\n"
            "  </head>\n"
            "  <body>\n"
            '    <div id="game-container"></div>\n'
            '    <script type="module" src="/src/main.js"></script>\n'
            "  </body>\n"
            "</html>\n"
        ),
        "src/sim.js": (
            "// Pure simulation core — NO Phaser, NO DOM. The headless invariant gate\n"
            "// runs THIS module in Node. All game state lives in one object advanced\n"
            "// by one step(state, input, dt); the Phaser scene only renders what step\n"
            "// returns, so there is never a second copy of the sim to desync from.\n\n"
            "export const WIDTH = 800\n"
            "export const HEIGHT = 600\n"
            "const PLAYER = 18      // half-extent of the player square\n"
            "const COIN = 12        // coin radius\n"
            "const SPEED = 260      // px/sec\n"
            "const TARGET = 10      // coins to win\n"
            "const TIME_LIMIT = 30  // seconds before time runs out\n\n"
            "// Seeded RNG (mulberry32) carried in state — NEVER Math.random, so the\n"
            "// simulation is fully reproducible (the gate's determinism check enforces it).\n"
            "function nextRandom(state) {\n"
            "  state.rng = (state.rng + 0x6d2b79f5) >>> 0\n"
            "  let t = state.rng\n"
            "  t = Math.imul(t ^ (t >>> 15), t | 1)\n"
            "  t ^= t + Math.imul(t ^ (t >>> 7), t | 61)\n"
            "  return ((t ^ (t >>> 14)) >>> 0) / 4294967296\n"
            "}\n\n"
            "function placeCoin(state) {\n"
            "  state.coin.x = COIN + nextRandom(state) * (WIDTH - 2 * COIN)\n"
            "  state.coin.y = COIN + nextRandom(state) * (HEIGHT - 2 * COIN)\n"
            "}\n\n"
            "export function createState(seed) {\n"
            "  const state = {\n"
            "    rng: (seed >>> 0) || 1,\n"
            "    player: { x: WIDTH / 2, y: HEIGHT / 2 },\n"
            "    coin: { x: 0, y: 0 },\n"
            "    score: 0,\n"
            "    timeLeft: TIME_LIMIT,\n"
            "    paused: false,\n"
            "    over: false,\n"
            "    won: false,\n"
            "  }\n"
            "  placeCoin(state)\n"
            "  return state\n"
            "}\n\n"
            "const clamp = (v, lo, hi) => (v < lo ? lo : v > hi ? hi : v)\n\n"
            "export function step(state, input, dt) {\n"
            "  // pause freezes the sim; game-over ignores input — both required by the gate.\n"
            "  if (state.paused || state.over) return state\n\n"
            "  const vx = (input.right ? 1 : 0) - (input.left ? 1 : 0)\n"
            "  const vy = (input.down ? 1 : 0) - (input.up ? 1 : 0)\n"
            "  state.player.x = clamp(state.player.x + vx * SPEED * dt, PLAYER, WIDTH - PLAYER)\n"
            "  state.player.y = clamp(state.player.y + vy * SPEED * dt, PLAYER, HEIGHT - PLAYER)\n\n"
            "  // Collision is a single distance test against the SAME coords we render —\n"
            "  // no separate physics body to fall out of sync with the sprite.\n"
            "  const dx = state.player.x - state.coin.x\n"
            "  const dy = state.player.y - state.coin.y\n"
            "  const reach = PLAYER + COIN\n"
            "  if (dx * dx + dy * dy <= reach * reach) {\n"
            "    state.score += 1\n"
            "    placeCoin(state)\n"
            "  }\n\n"
            "  state.timeLeft = Math.max(0, state.timeLeft - dt)\n"
            "  if (state.score >= TARGET) { state.won = true; state.over = true }\n"
            "  else if (state.timeLeft <= 0) { state.over = true }\n"
            "  return state\n"
            "}\n\n"
            "export function isWin(state) { return state.won }\n"
            "export function isLose(state) { return state.over && !state.won }\n"
        ),
        "src/main.js": _phaser_main_js(art),
        "src/styles.css": (
            ":root { font-family: system-ui, sans-serif; }\n"
            "body { margin: 0; background: #0f172a; display: grid; "
            "place-items: center; min-height: 100vh; }\n"
            "#game-container { line-height: 0; }\n"
            "canvas { max-width: 100%; height: auto; }\n"
        ),
        ".gitignore": "node_modules\ndist\n",
        "README.md": compose_readme(
            title,
            brief,
            stack_label="Phaser 3 + Vite",
            install="```bash\nnpm install\n```\n\nRequires Node.js 18+.",
            usage=(
                "Start the dev server with hot-reload:\n\n"
                "```bash\nnpm run dev\n```\n\n"
                "Build a production bundle and preview it:\n\n"
                "```bash\nnpm run build\nnpm run preview\n```"
            ),
            structure=[
                ("src/sim.js", "Pure game logic — createState/step/isWin/isLose (no Phaser; runs headless)"),
                ("src/main.js", "Phaser scene — renders the sim state and reads input (extend the visuals here)"),
                ("index.html", "HTML entry that mounts the Phaser canvas"),
                ("src/styles.css", "Page styles that center the game canvas"),
                ("vite.config.js", "Vite configuration (plain JS — no framework plugin)"),
                ("package.json", "Dependencies and npm scripts"),
            ],
            features=[
                "Pure simulation core (src/sim.js) separate from rendering — one authoritative state",
                "Deterministic, seeded logic that runs headless for automated correctness checks",
                "Single distance-based collision against the rendered coords (no desync)",
                "Production build + preview scripts",
            ],
        ),
    }


_BUILDERS: dict[str, Callable[[str, str], dict[str, str]]] = {
    "react_vite": _react_vite,
    "tauri": _tauri,
    "desktop": _tauri,
    "phaser": _phaser,
    "react_native": _react_native_expo,
    "nextjs": _nextjs,
    "astro": _astro,
    "remix": _remix,
    "static_html": _static_html,
    "python_cli": _python_cli,
    "fastapi": _fastapi,
    "node_express": _node_express,
}


def scaffold_for(
    stack: str, app_name: str, brief: str = "", *, art: bool = False
) -> dict[str, str]:
    """Return a ``{path: contents}`` mapping for a runnable project of ``stack``.

    Unknown stacks fall back to ``react_vite``. When the brief implies 3D/WebGL,
    the react/static web scaffolds ship a Three.js rotating-cube starter (a
    template variant, not a separate stack). ``art=True`` (game stacks) makes the
    scaffold preload role sprites and render them with a colored-primitive
    fallback; it never touches the pure sim core.
    """
    safe_name = (app_name or "app").strip() or "app"
    # Three.js template variant: keyword-guarded so normal builds are unchanged.
    if _implies_3d(brief):
        if stack == "react_vite":
            return _react_vite_threejs(safe_name, brief)
        if stack == "static_html":
            return _static_threejs(safe_name, brief)
    if stack == "phaser":
        return _phaser(safe_name, brief, art=art)
    builder = _BUILDERS.get(stack, _react_vite)
    return builder(safe_name, brief)


# ---- entrypoint synthesis (repair an agentic build with no runnable root) ----
# A coding agent often authors a real package (foo/manager.py, foo/cli.py, …)
# but forgets the runnable ROOT the rest of the pipeline (proof, boot, reviewer)
# expects. These pure helpers detect that and synthesize a real, wired
# ``main.py`` so ``python main.py`` actually runs the produced code — instead of
# the old behaviour of papering over it with an empty stub.

_ENTRYPOINT_BASENAMES = frozenset(
    {"main.py", "__main__.py", "app.py", "cli.py", "run.py", "manage.py", "wsgi.py", "asgi.py"}
)
# Module-level only (no leading indent): an indented ``def main(self)`` inside a
# class is a method, not an importable ``from module import main`` symbol.
_DEF_ENTRY_RE = _re.compile(r"^def\s+(main|run|cli)\s*\(", _re.MULTILINE)


def _norm(rel: str) -> str:
    return rel.replace("\\", "/")


def _module_path(rel: str) -> str:
    rel = _norm(rel)
    return rel[:-3].replace("/", ".") if rel.endswith(".py") else rel


def has_python_entrypoint(files: dict[str, str]) -> bool:
    """True if any file looks like a runnable Python entrypoint."""
    for rel in files:
        base = _norm(rel).rsplit("/", 1)[-1]
        if base in _ENTRYPOINT_BASENAMES:
            return True
    return False


def top_level_packages(files: dict[str, str]) -> list[str]:
    """Names of depth-1 packages (a dir directly holding ``__init__.py``)."""
    pkgs = {
        _norm(rel).split("/")[0]
        for rel in files
        if len(_norm(rel).split("/")) == 2 and _norm(rel).endswith("/__init__.py")
    }
    return sorted(pkgs)


def _find_entry_callable(files: dict[str, str]) -> tuple[str, str] | None:
    """Find a ``module, func`` exposing a callable named main/run/cli."""

    def rank(rel: str) -> int:
        base = _norm(rel).rsplit("/", 1)[-1]
        return {"cli.py": 0, "__main__.py": 1, "app.py": 2, "main.py": 3}.get(base, 9)

    for rel in sorted(files, key=rank):
        if not _norm(rel).endswith(".py"):
            continue
        m = _DEF_ENTRY_RE.search(files[rel] or "")
        if m:
            return _module_path(rel), m.group(1)
    return None


def synthesize_python_entrypoint(files: dict[str, str]) -> dict[str, str]:
    """Return ``{"main.py": <shim>}`` wiring an existing package to a root runner.

    Returns ``{}`` when the tree already has an entrypoint or there is nothing to
    wire. The shim imports the produced code so ``python main.py`` is genuinely
    runnable (and importable by the boot/proof checks).
    """
    if has_python_entrypoint(files):
        return {}
    target = _find_entry_callable(files)
    pkgs = top_level_packages(files)
    if target is None and not pkgs:
        return {}

    if target is not None:
        module, func = target
        shim = (
            '"""Application entrypoint (auto-wired by SkyN3t).\n\n'
            f"Delegates to ``{module}.{func}`` so ``python main.py`` runs the app.\n"
            '"""\n'
            "from __future__ import annotations\n\n"
            f"from {module} import {func} as _entry\n\n\n"
            "def main(argv: list[str] | None = None) -> int:\n"
            "    result = _entry()\n"
            "    return result if isinstance(result, int) else 0\n\n\n"
            'if __name__ == "__main__":\n'
            "    raise SystemExit(main())\n"
        )
        return {"main.py": shim}

    pkg = pkgs[0]
    shim = (
        '"""Application entrypoint (auto-generated by SkyN3t).\n\n'
        f"Best-effort runner: imports the ``{pkg}`` package and invokes its\n"
        "main()/run()/cli() if one exists.\n"
        '"""\n'
        "from __future__ import annotations\n\n"
        "import importlib\n\n"
        "_MODULES = (\n"
        f'    "{pkg}.cli",\n'
        f'    "{pkg}.__main__",\n'
        f'    "{pkg}.main",\n'
        f'    "{pkg}.app",\n'
        f'    "{pkg}",\n'
        ")\n"
        '_FUNCS = ("main", "run", "cli")\n\n\n'
        "def _resolve():\n"
        "    for name in _MODULES:\n"
        "        try:\n"
        "            mod = importlib.import_module(name)\n"
        "        except Exception:\n"
        "            continue\n"
        "        for fn in _FUNCS:\n"
        "            cand = getattr(mod, fn, None)\n"
        "            if callable(cand):\n"
        "                return cand\n"
        "    return None\n\n\n"
        "def main(argv: list[str] | None = None) -> int:\n"
        "    entry = _resolve()\n"
        "    if entry is None:\n"
        f'        print("{pkg}: imported OK, but no main()/run()/cli() entrypoint was found.")\n'
        "        return 0\n"
        "    result = entry()\n"
        "    return result if isinstance(result, int) else 0\n\n\n"
        'if __name__ == "__main__":\n'
        "    raise SystemExit(main())\n"
    )
    return {"main.py": shim}


def default_pyproject(slug: str) -> str:
    """A minimal but real pyproject for a python project keyed off the slug."""
    name = (slug or "app").strip() or "app"
    return (
        "[project]\n"
        f'name = "{name}"\n'
        'version = "0.1.0"\n'
        'requires-python = ">=3.10"\n\n'
        "[project.scripts]\n"
        f'{name} = "main:main"\n'
    )
