"""config_ui_agent — generate a settings/config UI + accessor for a built app.

The missing deliverable: when an app needs browser-supplied configuration (an API
key, an endpoint, a toggle), give the user a place to enter it. Given a project
dir + a :class:`ConfigSpec`, this writes:

* a framework-agnostic runtime accessor (``config.js`` / ``src/config.js``) that
  resolves each value from the in-app Settings (localStorage) -> build-time env
  (Vite/Node) -> default; and
* a **Settings screen** (a React component for React-family stacks, a vanilla
  ``settings.html`` page otherwise) with one field per client-scoped key.

Server-only keys (DB URLs, auth secrets) are NOT put in the browser — they stay in
``.env`` (handled by the PackagingAgent). Generation is deterministic string
templating (no LLM, never raises) and never overwrites an existing file unless
``overwrite=True``. Import has zero side effects.
"""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any

from skyn3t.agents.config_detector import detect_from_brief, detect_from_code
from skyn3t.core.agent import AgentCapability, BaseAgent, TaskRequest, TaskResult
from skyn3t.core.events import EventBus
from skyn3t.studio.config_spec import ConfigKey, ConfigSpec

# Stacks that get a React settings component vs. a vanilla HTML settings page.
# Next.js is file-routed, so it needs the settings UI emitted as a real route
# (app/settings/page.jsx), NOT an orphaned src/Settings.jsx nothing can reach.
_NEXT_FAMILY = frozenset({"nextjs", "next"})
_REACT_FAMILY = frozenset({"react", "react_vite", "vite"})
_STATIC_FAMILY = frozenset({"static", "static_html", "html"})
_OTHER_WEB = frozenset({"vue", "svelte", "astro", "remix"})
_WEB_STACKS = _NEXT_FAMILY | _REACT_FAMILY | _STATIC_FAMILY | _OTHER_WEB


def _keys_json(keys: list[ConfigKey]) -> str:
    return json.dumps([k.to_dict() for k in keys], indent=2)


def _config_js(client_keys: list[ConfigKey]) -> str:
    """Runtime accessor: localStorage -> import.meta.env -> process.env -> default."""
    return f"""\
// Auto-generated by SkyN3t — runtime configuration accessor.
// Resolves each value from the in-app Settings (localStorage), then build-time
// env (Vite/Node), then a default — so a fresh clone is configurable at runtime
// via the Settings screen AND via .env.
const STORAGE_KEY = 'skyn3t.config';

export const CONFIG_KEYS = {_keys_json(client_keys)};

function stored() {{
  try {{
    if (typeof localStorage !== 'undefined') {{
      return JSON.parse(localStorage.getItem(STORAGE_KEY) || '{{}}');
    }}
  }} catch (e) {{ /* ignore malformed storage */ }}
  return {{}};
}}

function fromEnv(name) {{
  try {{
    if (typeof import.meta !== 'undefined' && import.meta.env) {{
      const v = import.meta.env[name];
      if (v !== undefined && v !== '') return v;
    }}
  }} catch (e) {{ /* import.meta unavailable */ }}
  if (typeof process !== 'undefined' && process.env) {{
    const v = process.env[name];
    if (v !== undefined && v !== '') return v;
  }}
  return undefined;
}}

export function getConfig(name, fallback) {{
  const s = stored();
  if (s && s[name] !== undefined && s[name] !== '') return s[name];
  const e = fromEnv(name);
  if (e !== undefined) return e;
  const def = CONFIG_KEYS.find((k) => k.name === name);
  if (fallback !== undefined) return fallback;
  return def ? def.default : '';
}}

export function setConfig(values) {{
  try {{
    if (typeof localStorage !== 'undefined') {{
      const merged = Object.assign({{}}, stored(), values);
      localStorage.setItem(STORAGE_KEY, JSON.stringify(merged));
      return true;
    }}
  }} catch (e) {{ /* ignore */ }}
  return false;
}}

export function useConfig() {{
  const out = {{}};
  for (const k of CONFIG_KEYS) out[k.name] = getConfig(k.name);
  return out;
}}

export default useConfig;
"""


_SETTINGS_JSX_BODY = """\
import React, { useState } from 'react';
import { CONFIG_KEYS, getConfig, setConfig } from './config.js';

// Auto-generated by SkyN3t — lets the user supply the app's required
// configuration (API keys, endpoints, settings) at runtime, persisted locally.
export default function Settings() {
  const [values, setValues] = useState(() => {
    const init = {};
    for (const k of CONFIG_KEYS) init[k.name] = getConfig(k.name) || '';
    return init;
  });
  const [saved, setSaved] = useState(false);

  const onChange = (name, v) => {
    setValues((prev) => Object.assign({}, prev, { [name]: v }));
    setSaved(false);
  };
  const onSave = (e) => {
    e.preventDefault();
    setConfig(values);
    setSaved(true);
  };

  if (!CONFIG_KEYS.length) {
    return (
      <section style={{ maxWidth: 480, margin: '2rem auto' }}>
        <h2>Settings</h2>
        <p>No configuration required.</p>
      </section>
    );
  }

  return (
    <form onSubmit={onSave} style={{ maxWidth: 480, margin: '2rem auto', display: 'grid', gap: '1rem' }}>
      <h2>Settings</h2>
      {CONFIG_KEYS.map((k) => (
        <label key={k.name} style={{ display: 'grid', gap: '0.25rem' }}>
          <span>{k.name}{k.required ? ' *' : ''}</span>
          {k.description ? <small style={{ opacity: 0.7 }}>{k.description}</small> : null}
          <input
            type={k.kind === 'secret' || k.kind === 'api_key' ? 'password' : 'text'}
            value={values[k.name] || ''}
            placeholder={k.default || ''}
            onChange={(e) => onChange(k.name, e.target.value)}
          />
        </label>
      ))}
      <button type="submit">Save</button>
      {saved ? <span role="status">Saved locally.</span> : null}
    </form>
  );
}
"""


def _settings_jsx(config_import: str = "./config.js", *, use_client: bool = False) -> str:
    """A self-contained React Settings screen driven by CONFIG_KEYS.

    ``config_import`` sets the relative import path to the accessor; ``use_client``
    prepends the Next.js App-Router directive (the component uses useState, which a
    React Server Component cannot)."""
    body = _SETTINGS_JSX_BODY.replace("from './config.js'", "from '" + config_import + "'")
    return ("'use client';\n\n" + body) if use_client else body


def _settings_html(config_path: str) -> str:
    """A vanilla settings page for non-React web stacks (framework-agnostic)."""
    return f"""\
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Settings</title>
</head>
<body>
  <main style="max-width:480px;margin:2rem auto;font-family:system-ui,sans-serif">
    <h1>Settings</h1>
    <form id="settings-form" style="display:grid;gap:1rem"></form>
    <p id="settings-status" role="status"></p>
  </main>
  <!-- Auto-generated by SkyN3t — runtime configuration for this app. -->
  <script type="module">
    import {{ CONFIG_KEYS, getConfig, setConfig }} from '{config_path}';
    const form = document.getElementById('settings-form');
    const status = document.getElementById('settings-status');
    if (!CONFIG_KEYS.length) {{
      form.innerHTML = '<p>No configuration required.</p>';
    }} else {{
      for (const k of CONFIG_KEYS) {{
        const label = document.createElement('label');
        label.style.display = 'grid';
        label.style.gap = '0.25rem';
        const span = document.createElement('span');
        span.textContent = k.name + (k.required ? ' *' : '');
        const input = document.createElement('input');
        input.name = k.name;
        input.type = (k.kind === 'secret' || k.kind === 'api_key') ? 'password' : 'text';
        input.value = getConfig(k.name) || '';
        input.placeholder = k.default || '';
        label.appendChild(span);
        if (k.description) {{
          const small = document.createElement('small');
          small.textContent = k.description;
          label.appendChild(small);
        }}
        label.appendChild(input);
        form.appendChild(label);
      }}
      const btn = document.createElement('button');
      btn.type = 'submit';
      btn.textContent = 'Save';
      form.appendChild(btn);
      form.addEventListener('submit', (e) => {{
        e.preventDefault();
        const values = {{}};
        for (const k of CONFIG_KEYS) {{
          values[k.name] = form.elements[k.name].value;
        }}
        setConfig(values);
        status.textContent = 'Saved locally.';
      }});
    }}
  </script>
</body>
</html>
"""


def generate_config_ui(project_dir: str | Path, stack: str, spec: ConfigSpec,
                       *, overwrite: bool = False) -> list[str]:
    """Write a settings UI + accessor for the client-scoped keys in ``spec``.

    Returns the list of relative paths written (empty when the stack has no web
    UI, or the spec has no client keys to collect). Never raises for normal
    failures."""
    stack_l = (stack or "").strip().lower()
    client_keys = spec.client_keys()
    if stack_l not in _WEB_STACKS or not client_keys:
        return []

    root = Path(project_dir)
    if not root.is_dir():
        return []
    written: list[str] = []

    def write(rel: str, content: str) -> None:
        p = root / rel
        if p.exists() and not overwrite:
            return
        try:
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8")
            written.append(rel)
        except OSError:
            pass

    if stack_l in _STATIC_FAMILY:
        write("config.js", _config_js(client_keys))
        write("settings.html", _settings_html("./config.js"))
    elif stack_l in _NEXT_FAMILY:
        # File-routed: emit a REAL /settings route (App Router) that resolves to a
        # page, plus the accessor it imports — so it is actually reachable.
        write("app/config.js", _config_js(client_keys))
        write("app/settings/page.jsx", _settings_jsx("../config.js", use_client=True))
    elif stack_l in _REACT_FAMILY:
        write("src/config.js", _config_js(client_keys))
        write("src/Settings.jsx", _settings_jsx())
    else:  # other web frameworks: accessor + a framework-agnostic settings page
        write("src/config.js", _config_js(client_keys))
        write("settings.html", _settings_html("./src/config.js"))
    return written


# ---- static wiring verification ------------------------------------------

_HARDCODED_URL = re.compile(r"""['"](https?://[^'"\s]+)['"]""")
_ACCESSOR_NAMES = ("config.js", "config.py", "config.ts")
_SETTINGS_NAMES = ("Settings.jsx", "Settings.tsx", "settings.html", "Settings.vue")
_SCAN_EXTS = {".js", ".jsx", ".ts", ".tsx", ".mjs", ".vue", ".svelte", ".py", ".astro", ".html"}
_SKIP_DIRS = {"node_modules", ".git", "dist", "build", ".next", "__pycache__", ".venv"}


def _iter_source(root: Path):
    for p in root.rglob("*"):
        if not p.is_file() or p.suffix.lower() not in _SCAN_EXTS:
            continue
        if any(part in _SKIP_DIRS for part in p.relative_to(root).parts):
            continue
        yield p


def check_config_wiring(project_dir: str | Path, spec: ConfigSpec) -> dict[str, Any]:
    """Static check that config is surfaced + wired (never executes the app).

    Reports whether a settings UI + accessor exist when the spec needs them, and
    flags hardcoded http(s) URLs that should be configuration. Advisory: callers
    decide whether to act, so this never fails a build on its own."""
    root = Path(project_dir)
    files_list = [p for p in root.rglob("*") if p.is_file()]
    present = {p.name for p in files_list}
    rel_posix = [p.relative_to(root).as_posix().lower() for p in files_list]
    accessor = any(n in present for n in _ACCESSOR_NAMES)
    # A settings UI is a Settings component/page OR a file-routed settings route
    # (Next.js app/settings/page.* or pages/settings.*) — name-only detection
    # missed the latter and falsely reported "no settings UI".
    settings_route = any(
        rp.endswith(suffix)
        for rp in rel_posix
        for suffix in ("settings/page.jsx", "settings/page.tsx", "settings/page.js",
                       "pages/settings.jsx", "pages/settings.tsx", "pages/settings.js")
    )
    settings_ui = any(n in present for n in _SETTINGS_NAMES) or settings_route

    hardcoded: list[str] = []
    if root.is_dir():
        seen: set[str] = set()
        for p in _iter_source(root):
            if p.name in _SETTINGS_NAMES or p.name in _ACCESSOR_NAMES:
                continue
            try:
                text = p.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            for m in _HARDCODED_URL.finditer(text):
                url = m.group(1)
                # Localhost / schema / asset URLs aren't third-party config.
                if any(s in url for s in ("localhost", "127.0.0.1", "w3.org", "schema.org")):
                    continue
                if url not in seen:
                    seen.add(url)
                    hardcoded.append(url)

    # Advisory: is the accessor actually IMPORTED by real app code (not just the
    # Settings screen)? An accessor nothing imports is dead weight — surfaced for
    # observability but NOT a gap (whether app code uses it is codegen's call, so
    # we never fail a build on it).
    accessor_imported = False
    if accessor and root.is_dir():
        for p in _iter_source(root):
            relp = p.relative_to(root).as_posix().lower()
            if (p.name in _SETTINGS_NAMES or p.name in _ACCESSOR_NAMES
                    or "settings/page." in relp or relp.endswith("/settings.jsx")
                    or relp.endswith("/settings.tsx") or relp.endswith("/settings.js")):
                continue
            try:
                text = p.read_text(encoding="utf-8", errors="ignore")
            except OSError:
                continue
            if "getConfig" in text or "useConfig" in text or "config.js'" in text or 'config.js"' in text:
                accessor_imported = True
                break

    client_needed = bool(spec.client_keys())
    gaps: list[str] = []
    if client_needed and not settings_ui:
        gaps.append("app needs client config but has no settings UI")
    if not spec.is_empty() and not accessor:
        gaps.append("app needs config but has no config accessor module")
    for url in hardcoded[:10]:
        gaps.append(f"hardcoded URL should be configurable: {url}")

    return {
        "accessor_present": accessor,
        "settings_ui_present": settings_ui,
        "accessor_imported": accessor_imported,
        "hardcoded_urls": hardcoded[:10],
        "gaps": gaps,
        "ok": not gaps,
    }


def apply_config(project_dir: str | Path, brief: str, stack: str, *,
                 llm_fn: Any | None = None, overwrite: bool = False) -> dict[str, Any]:
    """Detect config (brief + code), generate the settings UI, verify wiring.

    The single entry point the runner and the improve engine both call. Returns a
    summary dict; never raises for normal failures."""
    spec = detect_from_brief(brief, stack, llm_fn=llm_fn).merge(detect_from_code(project_dir))
    files = generate_config_ui(project_dir, stack, spec, overwrite=overwrite)
    wiring = check_config_wiring(project_dir, spec)
    return {
        "config_spec": spec.to_dict(),
        "files_written": files,
        "wiring": wiring,
        "needs_config": not spec.is_empty(),
    }


class ConfigUIAgent(BaseAgent):
    """Agent wrapper so config-UI generation can run as a pipeline stage."""

    def __init__(self, name: str = "config_ui", event_bus: EventBus | None = None,
                 config: dict[str, Any] | None = None) -> None:
        super().__init__(name, agent_type="config_ui", provider="local",
                         event_bus=event_bus, config=config)
        self.add_capability(AgentCapability(
            name="config_ui",
            description="Generate a settings UI + accessor for required app config",
            tags=("packaging", "config"),
        ))

    async def initialize(self) -> None:
        self.metadata["ready"] = True

    async def health_check(self) -> bool:
        return True

    async def execute(self, task: TaskRequest) -> TaskResult:
        p = task.payload or {}
        target = p.get("project_dir") or p.get("worktree_dir") or p.get("dir")
        if not target:
            return TaskResult(task_id=task.task_id, success=False,
                              error="no project_dir in payload")
        summary = apply_config(
            target, p.get("brief", ""), p.get("stack", ""),
            overwrite=bool(p.get("overwrite", False)),
        )
        return TaskResult(task_id=task.task_id, success=True, output=summary)
