"""PackagingAgent — turn a raw scaffold into something a stranger can run.

Given a built project directory, it:

* detects the stack family (via :class:`StackDetector`),
* scans for required env vars (via :class:`EnvScanner`),
* writes the artifacts that make the project runnable by someone who just
  cloned it:

  - **web**: a config helper (``src/config.js`` exposing ``useConfig`` /
    ``Settings``), ``.gitignore``, ``README.md``.
  - **server**: ``Dockerfile``, ``docker-compose.yml``, ``.env.example``,
    plus ``.gitignore`` / ``README.md``.
  - **fullstack**: both of the above.

Everything is written *into the project dir under test* — never the repo. The
agent never overwrites an existing file unless ``overwrite=True`` is passed, so
it is safe by default (design rule #4).
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from skyn3t.agents._common import confined_path
from skyn3t.agents.env_scanner import EnvScanner, EnvScanResult
from skyn3t.agents.stack_detector import StackDetector, StackReport
from skyn3t.core.agent import AgentCapability, BaseAgent, TaskRequest, TaskResult
from skyn3t.core.events import EventBus

_GITIGNORE = """\
# dependencies
node_modules/
.pnp/
.venv/
venv/
__pycache__/
*.py[cod]

# build output
dist/
build/
.next/
.svelte-kit/
out/

# environment
.env
.env.local
.env.*.local

# logs / os
*.log
.DS_Store
"""


def _config_js(client_vars: list[str]) -> str:
    """Generate a tiny framework-agnostic config helper for the web app."""
    lines = [
        "// Auto-generated by SkyN3t PackagingAgent.",
        "// Centralizes runtime configuration so a fresh clone is configurable.",
        "",
        "function read(name, fallback) {",
        "  // Vite-style first, then Node/process, then a default.",
        "  try {",
        "    if (typeof import.meta !== 'undefined' && import.meta.env) {",
        "      const v = import.meta.env[name];",
        "      if (v !== undefined && v !== '') return v;",
        "    }",
        "  } catch (_) { /* import.meta unavailable */ }",
        "  if (typeof process !== 'undefined' && process.env) {",
        "    const v = process.env[name];",
        "    if (v !== undefined && v !== '') return v;",
        "  }",
        "  return fallback;",
        "}",
        "",
        "export const Settings = {",
    ]
    if client_vars:
        for v in client_vars:
            lines.append(f"  {v}: read('{v}', ''),")
    else:
        lines.append("  // No client env vars detected at packaging time.")
    lines += [
        "};",
        "",
        "export function useConfig() {",
        "  // Hook-friendly accessor; returns the resolved settings object.",
        "  return Settings;",
        "}",
        "",
        "export default Settings;",
        "",
    ]
    return "\n".join(lines)


def _dockerfile(report: StackReport) -> str:
    if "python" in report.languages:
        return (
            "# Auto-generated by SkyN3t PackagingAgent.\n"
            "FROM python:3.11-slim\n"
            "WORKDIR /app\n"
            "COPY requirements.txt* pyproject.toml* ./\n"
            "RUN pip install --no-cache-dir -r requirements.txt || pip install --no-cache-dir . || true\n"
            "COPY . .\n"
            "EXPOSE 8000\n"
            'CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]\n'
        )
    return (
        "# Auto-generated by SkyN3t PackagingAgent.\n"
        "FROM node:20-slim\n"
        "WORKDIR /app\n"
        "COPY package*.json ./\n"
        "RUN npm install --production || npm install\n"
        "COPY . .\n"
        "EXPOSE 3000\n"
        'CMD ["npm", "start"]\n'
    )


def _docker_compose(report: StackReport) -> str:
    port = "8000" if "python" in report.languages else "3000"
    return (
        "# Auto-generated by SkyN3t PackagingAgent.\n"
        "services:\n"
        "  app:\n"
        "    build: .\n"
        "    ports:\n"
        f'      - "{port}:{port}"\n'
        "    env_file:\n"
        "      - .env\n"
        "    restart: unless-stopped\n"
    )


def _env_example(env: EnvScanResult) -> str:
    lines = ["# Auto-generated by SkyN3t PackagingAgent.",
             "# Copy to .env and fill in real values."]
    if not env.variables:
        lines.append("# No environment variables detected.")
    for v in env.variables:
        lines.append(f"{v}=")
    return "\n".join(lines) + "\n"


def _readme(slug: str, report: StackReport, env: EnvScanResult) -> str:
    title = slug or "project"
    out = [f"# {title}", ""]
    out.append(
        f"A **{report.family}** project"
        + (f" built with {', '.join(report.frameworks)}" if report.frameworks else "")
        + ", packaged by SkyN3t so a fresh clone runs out of the box."
    )
    out.append("")

    # Features — derived from what the stack analysis found, so it is never empty.
    out += ["## Features", ""]
    feats: list[str] = []
    if report.has_web:
        feats.append("Web front-end")
    if report.has_server:
        feats.append("Dockerized backend service")
    for fw in report.frameworks:
        feats.append(f"{fw} integration")
    if env.variables:
        feats.append("Configurable via environment variables")
    if not feats:
        feats.append("Runnable starter project")
    out += [f"- {f}" for f in feats]
    out.append("")

    # Installation — concrete dependency-install commands for the detected stack.
    out += ["## Installation", ""]
    if report.has_web and "python" not in report.languages:
        out += ["```bash", "npm install", "```", ""]
    elif "python" in report.languages:
        out += ["```bash", "pip install -r requirements.txt", "```", ""]
    else:
        # No web/Python stack — never leave the section empty (header → header).
        out += ["See the project files for dependency requirements.", ""]

    out += ["## Usage", ""]
    if report.has_web and "python" not in report.languages:
        out += ["```bash", "npm run dev", "```", ""]
    if report.has_server:
        if "python" in report.languages:
            out += ["```bash", "python -m uvicorn main:app --reload", "```", ""]
        out += ["Or with Docker:", "", "```bash", "docker compose up --build", "```", ""]
    if not report.has_web and not report.has_server:
        out += ["See the project files for how to run it.", ""]

    if env.variables:
        out += ["## Configuration", "",
                "Copy `.env.example` to `.env` and set:", ""]
        for v in env.variables:
            out.append(f"- `{v}`")
        out.append("")

    out += ["## Project structure", "",
            "See the files in this directory; key entry points are listed above.", ""]
    return "\n".join(out)


class PackagingAgent(BaseAgent):
    """Makes a verified scaffold runnable by a stranger."""

    def __init__(self, name: str = "packaging", event_bus: EventBus | None = None,
                 config: dict[str, Any] | None = None) -> None:
        super().__init__(name, agent_type="packaging", provider="local",
                         event_bus=event_bus, config=config)
        self.add_capability(AgentCapability(
            name="package",
            description="Adds config/Docker/README so a scaffold is runnable",
            tags=("packaging",),
        ))

    async def initialize(self) -> None:
        self.metadata["ready"] = True

    @staticmethod
    def package_dir(directory: str | Path, slug: str = "",
                    overwrite: bool = False) -> dict[str, Any]:
        """Core packaging logic. Returns a summary dict; never raises for
        normal failures (returns ``ok: False`` instead)."""
        root = Path(directory)
        if not root.is_dir():
            return {"ok": False, "error": f"not a directory: {root}", "files_written": []}

        report = StackDetector.analyze(root)
        env = EnvScanner.scan(root)
        written: list[str] = []
        skipped: list[str] = []

        def write(rel: str, content: str) -> None:
            p = confined_path(root, rel)
            if p is None:  # symlinked subdir pointing outside the project tree
                skipped.append(f"{rel} (outside project root)")
                return
            if p.exists() and not overwrite:
                skipped.append(rel)
                return
            try:
                p.parent.mkdir(parents=True, exist_ok=True)
                p.write_text(content, encoding="utf-8")
                written.append(rel)
            except OSError as exc:  # pragma: no cover - fs failure
                skipped.append(f"{rel} ({exc})")

        # Common to everything.
        write(".gitignore", _GITIGNORE)
        write("README.md", _readme(slug, report, env))

        if report.has_web:
            write("src/config.js", _config_js(env.client_vars))

        if report.has_server:
            write("Dockerfile", _dockerfile(report))
            write("docker-compose.yml", _docker_compose(report))
            write(".env.example", _env_example(env))

        return {
            "ok": True,
            "family": report.family,
            "files_written": written,
            "skipped": skipped,
            "env_vars": env.variables,
            "frameworks": report.frameworks,
        }

    async def execute(self, task: TaskRequest) -> TaskResult:
        target = (task.payload.get("worktree_dir")
                  or task.payload.get("project_dir")
                  or task.payload.get("dir"))
        if not target:
            return TaskResult(task_id=task.task_id, success=False,
                              error="no project_dir in payload")
        slug = task.payload.get("slug", "")
        overwrite = bool(task.payload.get("overwrite", False))
        summary = self.package_dir(target, slug=slug, overwrite=overwrite)
        return TaskResult(task_id=task.task_id, success=summary.get("ok", False),
                          output=summary,
                          error=None if summary.get("ok") else summary.get("error"))

    async def health_check(self) -> bool:
        return True
