"""WriterAgent — generates project documentation (DOCS tier).

Writes a README into the worktree summarizing the project, how to run it, and
its structure. Offline it composes a real, useful README from the brief, stack,
and the files present in the worktree (design rule #1).
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Any

from skyn3t.adapters.llm import LLMClient
from skyn3t.agents._common import detect_stack, slugify
from skyn3t.core.agent import AgentCapability, BaseAgent, TaskRequest, TaskResult
from skyn3t.core.events import EventBus
from skyn3t.core.model_router import Tier

_SYSTEM = (
    "You are a technical writer. Write a clear, concise project README in "
    "Markdown: title, one-paragraph description, run instructions, and structure."
)

_RUN_HINTS: dict[str, str] = {
    "react_vite": "```bash\nnpm install\nnpm run dev\n```",
    "static_html": "Open `index.html` in a browser.",
    "python_cli": "```bash\npython main.py\n```",
    "fastapi": "```bash\npip install -r requirements.txt\nuvicorn main:app --reload\n```",
    "node_express": "```bash\nnpm install\nnpm start\n```",
}


class WriterAgent(BaseAgent):
    def __init__(self, name: str = "writer", *, event_bus: EventBus,
                 llm: LLMClient | None = None, config: dict | None = None) -> None:
        super().__init__(name, agent_type="documentation", provider="llm",
                         event_bus=event_bus, config=config)
        self.add_capability(AgentCapability(
            name="documentation", description="Write project documentation / README",
            tags=("generative", "docs")))
        self.llm = llm

    async def initialize(self) -> None:
        if self.llm is None:
            self.llm = LLMClient()
        self.metadata["backend"] = self.llm.backend

    async def execute(self, task: TaskRequest) -> TaskResult:
        p = task.payload
        brief = p.get("brief", "") or p.get("slug", "app")
        title = slugify(p.get("slug") or brief, "app")
        stack = detect_stack(brief=brief, plan=p.get("plan"), explicit=p.get("stack", ""))
        worktree = p.get("worktree_dir") or p.get("project_dir")
        file_list = self._list_files(worktree)

        if self.llm.backend != "stub":
            prompt = (
                f"Brief: {brief}\nStack: {stack}\nFiles: {file_list}\n\n"
                "Write the README.md."
            )
            try:
                result = await self.llm.complete(prompt, tier=Tier.DOCS, system=_SYSTEM,
                                                 max_tokens=2048)
                readme = result.text.strip() or self._offline_readme(title, brief, stack, file_list)
                model, backend = result.model, result.backend
            except Exception:  # noqa: BLE001
                readme = self._offline_readme(title, brief, stack, file_list)
                model, backend = "offline", "stub"
        else:
            readme = self._offline_readme(title, brief, stack, file_list)
            model, backend = "offline", "stub"

        written_path: str | None = None
        if worktree:
            try:
                path = Path(worktree)
                path.mkdir(parents=True, exist_ok=True)
                target = path / "README.md"
                target.write_text(readme, encoding="utf-8")
                written_path = str(target)
            except OSError:
                written_path = None

        return TaskResult(task_id=task.task_id, success=True,
                          output={"readme": readme, "path": written_path,
                                  "model": model, "backend": backend})

    def _offline_readme(self, title: str, brief: str, stack: str,
                        files: list[str]) -> str:
        run = _RUN_HINTS.get(stack, "")
        structure = "\n".join(f"- `{f}`" for f in files) if files else "_(no files yet)_"
        return (
            f"# {title}\n\n"
            f"{brief or 'A project generated by SkyN3t.'}\n\n"
            f"**Stack:** {stack}\n\n"
            "## Run\n\n"
            f"{run}\n\n"
            "## Structure\n\n"
            f"{structure}\n\n"
            "---\n_Generated by SkyN3t._\n"
        )

    @staticmethod
    def _list_files(worktree: Any) -> list[str]:
        if not worktree:
            return []
        root = Path(worktree)
        if not root.is_dir():
            return []
        out: list[str] = []
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [d for d in dirnames if d not in {"node_modules", ".git", "dist", "__pycache__"}]
            for fn in filenames:
                rel = os.path.relpath(os.path.join(dirpath, fn), root)
                out.append(rel)
        return sorted(out)[:50]

    async def health_check(self) -> bool:
        return self.llm is not None
