"""The Ship pillar — turn a proven build into a concrete plan to go live.

skyn3t builds + proves + previews LOCALLY (``app_runner`` is localhost-only).
This module classifies a build and emits a KEYLESS, one-command deploy plan:
the right hosts, the exact command, and — for server stacks — a ready Dockerfile.
No token, no network: it is the honest "…and here's how it ships" answer for
every stack the builder can produce, or an honest "not a hosted app" verdict.

Registry-driven (the same idiom as ``core.stacks``): every builder stack maps to
a deploy KIND, so a new stack is never silently un-shippable. The planner stays
side-effect free so its output can be inspected and persisted safely; REAL,
token-gated execution lives in :func:`execute_deploy` below (the
``skyn3t deploy --now --execute`` path) and in the Settings-gated
:class:`skyn3t.agents.deploy_agent.DeployAgent`.
"""

from __future__ import annotations

import json
import os
import re
import shlex
import shutil
import subprocess
from collections.abc import Mapping
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from time import time
from typing import Any
from urllib.parse import urlsplit

# stack (agent vocab + planner aliases) -> deploy kind. Every KNOWN_STACKS entry
# is present (a drift test asserts it). Kinds:
#   static    — a built static bundle → a static host (Cloudflare Pages/Netlify)
#   node_ssr  — a full-stack Node app → Vercel / a Node container
#   container — an HTTP server → Fly / Railway (Dockerfile emitted)
#   artifact  — not a hosted URL: a publishable/runnable binary or package
#   mobile    — an app binary → Expo EAS
DEPLOY_KIND: dict[str, str] = {
    # static-hostable web builds
    "react_vite": "static", "react": "static", "react_ts": "static",
    "vue": "static", "sveltekit": "node_ssr",
    "static_html": "static", "static": "static",
    "astro": "static", "phaser": "static",
    # full-stack Node (SSR/routing) — not a plain static drop
    "nextjs": "node_ssr", "next": "node_ssr", "remix": "node_ssr",
    # HTTP servers → container
    "fastapi": "container", "rag": "container", "workflow": "container",
    "node_express": "container", "express": "container",
    # not web-hosted: distributable artifacts
    "python_cli": "artifact", "python": "artifact", "cli": "artifact",
    "agent_pack": "artifact", "mcp": "artifact",
    "swift": "artifact", "tauri": "artifact", "desktop": "artifact",
    # mobile app binary
    "react_native": "mobile", "swift_ios": "mobile",
}

_PY_DOCKERFILE = (
    "# Generated by skyn3t — a container image for this FastAPI/Python server.\n"
    "FROM python:3.11-slim\n"
    "WORKDIR /app\n"
    "COPY requirements.txt ./\n"
    "RUN pip install --no-cache-dir -r requirements.txt\n"
    "COPY . .\n"
    "# Platforms (Fly/Railway) inject $PORT.\n"
    "ENV PORT=8080\n"
    "EXPOSE 8080\n"
    'CMD ["sh", "-c", "uvicorn __ASGI_TARGET__ --host 0.0.0.0 --port ${PORT:-8080}"]\n'
)

_NODE_DOCKERFILE = (
    "# Generated by skyn3t — a container image for this Node server.\n"
    "FROM node:20-slim\n"
    "WORKDIR /app\n"
    "COPY package*.json ./\n"
    "RUN npm ci --omit=dev || npm install --omit=dev\n"
    "COPY . .\n"
    "ENV PORT=8080\n"
    "EXPOSE 8080\n"
    'CMD ["npm", "start"]\n'
)

_DOCKERIGNORE = (
    ".git\n"
    ".git-credentials\n"
    ".env\n"
    ".env.*\n"
    ".dev.vars*\n"
    ".npmrc\n"
    ".netrc\n"
    ".pypirc\n"
    ".aws\n"
    ".azure\n"
    ".docker\n"
    ".kube\n"
    ".ssh\n"
    ".terraform\n"
    ".terraformrc\n"
    ".vault-token\n"
    ".wrangler\n"
    ".vercel\n"
    ".netlify\n"
    ".railway\n"
    ".skyn3t\n"
    ".venv\n"
    "__pycache__\n"
    "*.py[cod]\n"
    "*.pem\n"
    "*.key\n"
    "*.p12\n"
    "*.pfx\n"
    "*.jks\n"
    "*.keystore\n"
    "id_rsa\n"
    "id_ed25519\n"
    "application_default_credentials.json\n"
    "pip.conf\n"
    "pip.ini\n"
    "credentials.json\n"
    "secrets.json\n"
    "skyn3t_manifest.json\n"
    "node_modules\n"
    ".pytest_cache\n"
    ".mypy_cache\n"
    ".coverage\n"
    "coverage\n"
    "tests\n"
    "test_*\n"
)


@dataclass(slots=True)
class DeployPlan:
    """A concrete, keyless plan to put a build on the internet (or distribute it)."""

    deployable: bool = False
    kind: str = "none"
    targets: list[str] = field(default_factory=list)
    command: str = ""
    build_command: str = ""
    output_dir: str = "."
    artifacts: dict[str, str] = field(default_factory=dict)
    serves_url: bool = False
    notes: str = ""
    env_vars: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "deployable": self.deployable,
            "kind": self.kind,
            "targets": list(self.targets),
            "command": self.command,
            "build_command": self.build_command,
            "output_dir": self.output_dir,
            "artifacts": dict(self.artifacts),
            "serves_url": self.serves_url,
            "notes": self.notes,
            "env_vars": list(self.env_vars),
        }


def deployment_quality_gate(manifest: Any | None) -> dict[str, Any]:
    """Return the objective evidence required before a remote deployment.

    A completed/GO label is not sufficient on its own: older, interrupted, or
    externally edited manifests can carry those strings without a proof run.
    Remote entrypoints share this helper so CLI, web, and agent dispatch cannot
    silently disagree about whether an artifact is proven.
    """
    if manifest is None:
        status = ""
        verdict = ""
        extra: dict[str, Any] = {}
    elif isinstance(manifest, dict):
        status = str(manifest.get("status") or "").strip().lower()
        verdict = str(manifest.get("verdict") or "").strip().lower()
        raw_extra = manifest.get("extra")
        extra = raw_extra if isinstance(raw_extra, dict) else {}
    else:
        status = str(getattr(manifest, "status", "") or "").strip().lower()
        verdict = str(getattr(manifest, "verdict", "") or "").strip().lower()
        raw_extra = getattr(manifest, "extra", None)
        extra = raw_extra if isinstance(raw_extra, dict) else {}

    proof_present = isinstance(extra.get("proof"), dict)
    proof = extra.get("proof") if proof_present else None
    proof_passed = proof.get("passed") is True if isinstance(proof, dict) else None
    blockers: list[str] = []
    if status != "completed":
        blockers.append("build status must be completed")
    if verdict != "go":
        blockers.append("build verdict must be GO")
    if not proof_present:
        blockers.append("objective build proof is required")
    elif proof_passed is not True:
        blockers.append("build proof exists but did not pass")
    return {
        "passed": not blockers,
        "status": status,
        "verdict": verdict,
        "proof_present": proof_present,
        "proof_passed": proof_passed,
        "blockers": blockers,
    }


def _normalize(stack: str) -> str:
    s = (stack or "").strip().lower()
    if s in DEPLOY_KIND:
        return s
    try:
        from skyn3t.agents._common import _normalize_stack

        return _normalize_stack(s) or s
    except Exception:  # noqa: BLE001 - deploy planning must never raise
        return s


def _path_is_link_like(path: Path) -> bool:
    try:
        if path.is_symlink():
            return True
        is_junction = getattr(path, "is_junction", None)
        return bool(is_junction and is_junction())
    except OSError:
        return True


def _safe_project_file(project_dir: Path, path: Path) -> bool:
    try:
        return (
            path.is_file()
            and not _path_is_link_like(path)
            and path.resolve(strict=True).is_relative_to(project_dir.resolve(strict=True))
        )
    except OSError:
        return False


def _detect_kind(project_dir: Path, stack: str) -> str:
    """The deploy kind for a stack; when the stack is unknown/empty, fall back to
    content detection via the same run-spec the local preview uses."""
    norm = _normalize(stack)
    if norm == "sveltekit":
        return "static" if _sveltekit_is_static(project_dir) else "node_ssr"
    if norm in DEPLOY_KIND:
        return DEPLOY_KIND[norm]
    try:
        from skyn3t.studio.app_runner import build_run_spec

        spec = build_run_spec(project_dir, stack, port=0)
    except Exception:  # noqa: BLE001
        spec = None
    if spec is None:
        return "none"
    if spec.kind == "python_web":
        return "container"
    if spec.kind == "static":
        return "static"
    if spec.kind == "node":
        return "node_ssr" if _is_ssr_node(project_dir) else "static"
    return "none"


def _has_build_script(project_dir: Path) -> bool:
    pkg = project_dir / "package.json"
    if not _safe_project_file(project_dir, pkg):
        return False
    try:
        scripts = (json.loads(pkg.read_text(encoding="utf-8")) or {}).get("scripts") or {}
    except (OSError, ValueError):
        return False
    return "build" in scripts


def _is_ssr_node(project_dir: Path) -> bool:
    """True when a Node project is a server-rendered framework (Next.js/Remix)
    rather than a plain static SPA (Vite/CRA). Modern Next uses
    ``next.config.mjs``/``.ts`` or *no* config at all, so checking only
    ``next.config.js`` (the old code) misclassifies most current Next apps as
    static and would route them to a static host — breaking SSR/API routes. We
    check config files AND package.json deps/scripts."""
    for name in ("next.config.js", "next.config.mjs", "next.config.ts",
                 "next.config.cjs", "remix.config.js"):
        if _safe_project_file(project_dir, project_dir / name):
            return True
    pkg = project_dir / "package.json"
    if not _safe_project_file(project_dir, pkg):
        return False
    try:
        data = json.loads(pkg.read_text(encoding="utf-8")) or {}
    except (OSError, ValueError):
        return False
    deps = {**(data.get("dependencies") or {}), **(data.get("devDependencies") or {})}
    if "next" in deps or any(k.startswith("@remix-run/") for k in deps):
        return True
    scripts = " ".join(str(v) for v in (data.get("scripts") or {}).values())
    return bool(re.search(r"\b(next|remix)\b", scripts))


def _sveltekit_is_static(project_dir: Path) -> bool:
    """Return true only when SvelteKit explicitly uses adapter-static.

    ``adapter-auto`` can select an SSR platform adapter at deploy time and does
    not produce a generic ``dist`` tree. Treating every SvelteKit project as a
    static Vite app created plans that could never upload the built application.
    """
    config_text = ""
    for name in (
        "svelte.config.js",
        "svelte.config.mjs",
        "svelte.config.ts",
        "svelte.config.cjs",
    ):
        path = project_dir / name
        if not _safe_project_file(project_dir, path):
            continue
        try:
            config_text += "\n" + path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
    if "@sveltejs/adapter-static" in config_text or "adapter-static" in config_text:
        return True
    pkg = project_dir / "package.json"
    if _safe_project_file(project_dir, pkg):
        try:
            data = json.loads(pkg.read_text(encoding="utf-8")) or {}
            deps = {**(data.get("dependencies") or {}), **(data.get("devDependencies") or {})}
            return "@sveltejs/adapter-static" in deps
        except (OSError, ValueError, TypeError):
            pass
    return False


def _existing_static_output(project_dir: Path) -> str | None:
    """Return a real built static artifact, preferring framework outputs."""
    for relative in ("dist", "build", "out"):
        candidate = project_dir / relative
        if (
            candidate.is_dir()
            and not _path_is_link_like(candidate)
            and _safe_project_file(project_dir, candidate / "index.html")
        ):
            return relative
    return "." if _safe_project_file(project_dir, project_dir / "index.html") else None


def _static_output_dir(project_dir: Path, stack: str, built: bool) -> str:
    existing = _existing_static_output(project_dir)
    if existing and (existing != "." or not built):
        return existing
    if _normalize(stack) == "sveltekit" and _sveltekit_is_static(project_dir):
        return "build"
    return "dist" if built else "."


def _python_asgi_target(project_dir: Path) -> str:
    """Find the FastAPI/Starlette application import used by the container."""
    candidates = sorted(
        (
            path for path in project_dir.rglob("*.py")
            if _safe_project_file(project_dir, path)
            if len(path.relative_to(project_dir).parts) <= 4
            and not any(
                part.lower() in {"tests", ".venv", "venv", "__pycache__"}
                for part in path.relative_to(project_dir).parts
            )
        ),
        key=lambda path: (
            path.name != "main.py",
            len(path.relative_to(project_dir).parts),
            path.as_posix(),
        ),
    )
    assignment = re.compile(
        r"(?m)^\s*([A-Za-z_]\w*)\s*=\s*(?:FastAPI|Starlette)\s*\("
    )
    for path in candidates:
        try:
            source = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        match = assignment.search(source)
        if match is None:
            continue
        relative = path.relative_to(project_dir).with_suffix("")
        if not all(part.isidentifier() for part in relative.parts):
            continue
        return f"{'.'.join(relative.parts)}:{match.group(1)}"
    return "main:app"


def _apply_target(requested: str | None, pairs: list[tuple[str, str]]) -> tuple[list[str], str, str]:
    """Honor a user's ``--target`` preference. ``pairs`` is an ordered list of
    ``(host, deploy-command)``; the first is the default. Returns
    ``(ordered_targets, command, note_suffix)``: when ``requested`` is a valid
    host for this kind it is moved to the front and its command is chosen; when
    it is given but unavailable, the default is kept and a note explains why;
    when it is empty, the default order/command is returned unchanged."""
    names = [p[0] for p in pairs]
    cmds = dict(pairs)
    if requested and requested in cmds:
        ordered = [requested] + [n for n in names if n != requested]
        return ordered, cmds[requested], ""
    note = ""
    if requested and requested not in cmds:
        note = (f" (requested target '{requested}' isn't available for this build; "
                f"using {names[0]})")
    return names, cmds[names[0]], note


def _provider_project_name(project_dir: Path) -> str:
    """Return a conservative provider-compatible project/site name."""
    normalized = re.sub(r"[^a-z0-9-]+", "-", project_dir.name.lower())
    normalized = re.sub(r"-{2,}", "-", normalized).strip("-")
    return (normalized or "skyn3t-app")[:63].rstrip("-")


# Environment reads the operator must satisfy at deploy time. Regex-based and
# offline: each pattern captures the variable NAME from one read idiom —
# process.env.NAME, import.meta.env.VITE_NAME, os.getenv("NAME"),
# os.environ["NAME"], os.environ.get("NAME").
_PROCESS_ENV_RE = re.compile(r"\bprocess\.env\.([A-Za-z_][A-Za-z0-9_]*)")
_IMPORT_META_ENV_RE = re.compile(r"\bimport\.meta\.env\.([A-Za-z_][A-Za-z0-9_]*)")
_PY_ENV_RE = re.compile(
    r"\bos\.(?:getenv\(\s*|environ\[\s*|environ\.get\(\s*)['\"]([A-Za-z_][A-Za-z0-9_]*)['\"]"
)
# Vite injects these build-time meta vars itself; they are not operator config.
_VITE_META_VARS = {"MODE", "BASE_URL", "PROD", "DEV", "SSR"}
_ENV_SOURCE_SUFFIXES = {
    ".py", ".js", ".jsx", ".ts", ".tsx", ".mjs", ".cjs", ".vue", ".svelte", ".astro",
}
_ENV_SKIP_DIRS = {"node_modules", ".next", "dist", "build", "out", ".venv", "venv", "__pycache__", ".git"}


def _scan_env_vars(project_dir: Path) -> list[str]:
    """Return the sorted, deduplicated env vars the project source reads.
    Same file-selection posture as the other offline scans: source suffixes
    only, dependency/build dirs skipped, link-like files never followed."""
    found: set[str] = set()
    for path in project_dir.rglob("*"):
        if any(part in _ENV_SKIP_DIRS for part in path.relative_to(project_dir).parts):
            continue
        if path.suffix.lower() not in _ENV_SOURCE_SUFFIXES:
            continue
        if not _safe_project_file(project_dir, path):
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        found.update(_PROCESS_ENV_RE.findall(text))
        found.update(
            name for name in _IMPORT_META_ENV_RE.findall(text) if name not in _VITE_META_VARS
        )
        found.update(_PY_ENV_RE.findall(text))
    return sorted(found)


def plan_deploy(project_dir: str | Path, stack: str = "", *, target: str | None = None) -> DeployPlan:
    """Classify ``project_dir`` and return a keyless :class:`DeployPlan`. Never
    raises; a missing dir or unknown stack still yields a sane plan.

    ``target`` is an optional preferred host (e.g. ``"vercel"``, ``"fly"``):
    when it is a valid host for the detected kind it is moved to the front of
    ``targets`` and its host-specific ``command`` is chosen; an unavailable
    target keeps the default and is explained in ``notes``.

    Every plan also carries ``env_vars`` — the sorted, deduplicated environment
    variables the project source reads — rendered into ``notes`` as a
    "Required environment variables" section so the operator knows what to set
    before deploying (or "none detected")."""
    plan = _plan_deploy(project_dir, stack, target=target)
    try:
        pdir = Path(project_dir)
        if pdir.is_dir() and not _path_is_link_like(pdir):
            plan.env_vars = _scan_env_vars(pdir)
    except Exception:  # noqa: BLE001 - the env scan must never break planning
        plan.env_vars = []
    section = (
        "Required environment variables: " + ", ".join(plan.env_vars)
        if plan.env_vars
        else "Required environment variables: none detected"
    )
    plan.notes = f"{plan.notes}\n{section}" if plan.notes else section
    return plan


def _plan_deploy(project_dir: str | Path, stack: str = "", *, target: str | None = None) -> DeployPlan:
    """Classify the build and pick a deploy kind/targets (see :func:`plan_deploy`,
    which layers the env-var manifest on top). Never raises."""
    try:
        pdir = Path(project_dir)
        if not pdir.is_dir() or _path_is_link_like(pdir):
            return DeployPlan(
                deployable=False,
                kind="none",
                notes="Deploy planning requires a real, non-linked project directory.",
            )
        kind = _detect_kind(pdir, stack)

        if kind == "static":
            built = _has_build_script(pdir)
            out = _static_output_dir(pdir, stack, built)
            project_name = _provider_project_name(pdir)
            vercel_name = "" if (pdir / ".vercel" / "project.json").is_file() else (
                f" --name {project_name}"
            )
            netlify_site = "" if (pdir / ".netlify" / "state.json").is_file() else (
                f" --site-name {project_name}"
            )
            targets, command, note = _apply_target(target, [
                ("vercel", f"vercel deploy {out} --prod --yes{vercel_name}"),
                (
                    "netlify",
                    f"netlify deploy --prod --json --no-build --dir {out}{netlify_site}",
                ),
                (
                    "cloudflare-pages",
                    f"wrangler pages deploy {out} --project-name {project_name}",
                ),
            ])
            return DeployPlan(
                deployable=True, kind="static", serves_url=True,
                targets=targets, output_dir=out,
                build_command="npm run build" if built else "",
                command=command,
                notes=(
                    "A static bundle — Vercel is the zero-config default; Netlify "
                    "creates or reuses a site, while Cloudflare Pages requires a "
                    "matching account/project."
                    + note
                ),
            )

        if kind == "node_ssr":
            fly_command = (
                "flyctl deploy --remote-only --yes"
                if (pdir / "fly.toml").is_file()
                else "flyctl launch --yes"
            )
            targets, command, note = _apply_target(target, [
                ("vercel", "vercel deploy --prod --yes"),
                ("railway", "railway up --ci"),
                ("fly", fly_command),
            ])
            return DeployPlan(
                deployable=True, kind="node_ssr", serves_url=True,
                targets=targets, output_dir=".", build_command="",
                command=command,
                notes="A full-stack Node app — Vercel is zero-config; Railway/Fly work via a Node container." + note,
            )

        if kind == "container":
            norm = _normalize(stack)
            dockerfile = (
                _NODE_DOCKERFILE
                if norm in ("node_express", "express")
                else _PY_DOCKERFILE.replace(
                    "__ASGI_TARGET__", _python_asgi_target(pdir)
                )
            )
            fly_command = (
                "flyctl deploy --remote-only --yes"
                if (pdir / "fly.toml").is_file()
                else "flyctl launch --dockerfile Dockerfile --yes"
            )
            targets, command, note = _apply_target(target, [
                ("fly", fly_command),
                ("railway", "railway up --ci"),
            ])
            return DeployPlan(
                deployable=True, kind="container", serves_url=True,
                targets=targets, output_dir=".", build_command="",
                command=command,
                artifacts={"Dockerfile": dockerfile, ".dockerignore": _DOCKERIGNORE},
                notes=("An HTTP server — ships as a container to Fly or Railway. "
                       "Set any keys as platform secrets." + note),
            )

        if kind == "mobile":
            norm = _normalize(stack)
            if norm == "swift_ios":
                targets, command, note = _apply_target(target, [
                    ("xcode-testflight", "xcodebuild -project App.xcodeproj -scheme App -configuration Release archive"),
                ])
                return DeployPlan(
                    deployable=True, kind="mobile", serves_url=False,
                    targets=targets, output_dir=".", build_command="", command=command,
                    notes=("A native iOS app — archive/sign in Xcode, then upload to TestFlight "
                           "or install it on a registered device." + note),
                )
            targets, command, note = _apply_target(target, [
                ("expo-eas", "eas build --platform all"),
            ])
            return DeployPlan(
                deployable=True, kind="mobile", serves_url=False,
                targets=targets, output_dir=".", build_command="",
                command=command,
                notes="A mobile app — build stores/installable binaries via Expo EAS." + note,
            )

        if kind == "artifact":
            norm = _normalize(stack)
            if norm in ("python_cli", "python", "cli", "mcp"):
                pairs = [
                    ("pypi", "python -m build && python -m twine upload dist/*"),
                    ("github-release", "gh release create v0.1.0 dist/*"),
                ]
                output = "dist"
            else:  # agent_pack, swift, tauri, desktop
                pairs = [("github-release", "gh release create v0.1.0 <built-artifact>")]
                output = "."
            targets, command, note = _apply_target(target, pairs)
            return DeployPlan(
                deployable=True, kind="artifact", serves_url=False,
                targets=targets, output_dir=output, build_command="",
                command=command,
                notes="Not a hosted URL — a distributable package/binary. Publish, don't serve." + note,
            )

        return DeployPlan(deployable=False, kind="none",
                          notes="No hosted deploy path detected for this build.")
    except Exception as exc:  # noqa: BLE001 - a planner must never break a build
        return DeployPlan(deployable=False, kind="none", notes=f"deploy planning error: {exc}")


def write_deploy_artifacts(plan: DeployPlan, project_dir: str | Path) -> list[str]:
    """Write the plan's artifacts (e.g. a Dockerfile) into the project — but
    NEVER clobber a user-authored file of the same name. Returns the names
    written. Never raises."""
    written: list[str] = []
    pdir = Path(project_dir)
    for name, content in (plan.artifacts or {}).items():
        relative = Path(name)
        if relative.is_absolute() or ".." in relative.parts or _path_is_link_like(pdir):
            continue
        target = pdir / relative
        cursor = pdir
        unsafe_link = False
        for part in relative.parts:
            cursor = cursor / part
            if _path_is_link_like(cursor):
                unsafe_link = True
                break
        try:
            target.resolve(strict=False).relative_to(pdir.resolve())
        except (OSError, ValueError):
            continue
        if unsafe_link or target.exists():
            continue  # non-destructive: respect a hand-authored file
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            written.append(name)
        except OSError:
            continue
    return written


def apply_deploy_health_gate(
    result: dict[str, Any],
    deploy_check: dict[str, Any],
) -> dict[str, Any]:
    """Attach live-health evidence and decide whether a deploy may become active.

    A provider can successfully create a deployment that is unhealthy or cannot
    yet be verified. Preserve that remote execution truth and URL, but make the
    overall result unsuccessful so :func:`record_deployment` cannot advance the
    manifest's active pointer.
    """
    gated = dict(result or {})
    check = dict(deploy_check or {})
    gated["deploy_check"] = check
    if not (gated.get("ok") and gated.get("url")):
        return gated
    if check.get("ok") is True and not check.get("skipped"):
        return gated

    skipped = bool(check.get("skipped"))
    issues = check.get("issues")
    issue_text = "; ".join(
        str(item) for item in issues if str(item).strip()
    ) if isinstance(issues, list) else ""
    detail = str(check.get("reason") or issue_text or "live URL did not pass health verification")
    if issue_text and issue_text not in detail:
        detail = f"{detail}: {issue_text}"
    gated.update({
        "provider_command_ok": True,
        "provider_status": str(gated.get("status") or "succeeded"),
        "ok": False,
        "status": "deployed_unverified" if skipped else "deployed_unhealthy",
        "activation_blocked": True,
        "activation_blocker": "deploy_check_skipped" if skipped else "deploy_check_failed",
        "error": f"provider deployed the URL, but activation was blocked: {detail}",
    })
    return gated


def record_deployment(
    project_dir: str | Path,
    *,
    result: dict[str, Any],
    plan: DeployPlan,
    target: str,
) -> dict[str, Any]:
    """Persist a deployment attempt and its execution evidence.

    Records are append-only under ``extra.deployments``. Only a successful result
    with a URL advances the manifest's ``live_url`` pointer. Never raises; returns
    the record it attempted to persist.
    """
    result = result or {}
    url = str(result.get("url") or "")
    ok = bool(result.get("ok"))
    provider = str(result.get("provider") or result.get("target") or "")
    raw_commands = result.get("commands")
    commands = [dict(item) for item in raw_commands if isinstance(item, dict)] \
        if isinstance(raw_commands, list) else []
    record = {
        "ts": time(),
        "target": str(target or result.get("target") or ""),
        "provider": provider,
        "url": url,
        "kind": plan.kind,
        "serves_url": bool(plan.serves_url),
        "ok": ok,
        "status": str(result.get("status") or ("succeeded" if ok else "failed")),
        "commands": commands,
        "remote_deploy_attempted": bool(result.get("remote_deploy_attempted")),
        "remote_deploy_performed": result.get("remote_deploy_performed", False),
        "remote_state": str(result.get("remote_state") or "not_started"),
        "manifest_pointer_active": bool(ok and url),
        "persisted": False,
    }
    if "provider_command_ok" in result:
        record["provider_command_ok"] = bool(result.get("provider_command_ok"))
    if result.get("provider_status"):
        record["provider_status"] = str(result.get("provider_status"))
    if result.get("activation_blocked"):
        record["activation_blocked"] = True
        record["activation_blocker"] = str(result.get("activation_blocker") or "")
    deploy_check = result.get("deploy_check")
    if isinstance(deploy_check, dict):
        record["deploy_check"] = dict(deploy_check)
    if result.get("error"):
        record["error"] = str(result.get("error"))
    if result.get("output_tail"):
        record["output_tail"] = str(result.get("output_tail"))[-500:]
    try:
        from skyn3t.studio.manifest import BuildManifest

        pdir = Path(project_dir)
        manifest = BuildManifest.load(pdir)
        if manifest is None:
            record["persistence_error"] = "manifest not found"
            return record
        deployments = manifest.extra.get("deployments")
        if not isinstance(deployments, list):
            deployments = []
        if ok and url:
            for previous in deployments:
                if isinstance(previous, dict):
                    previous["manifest_pointer_active"] = False
        deployments.append(record)
        manifest.extra["deployments"] = deployments[-20:]
        if isinstance(deploy_check, dict):
            # The latest attempt's evidence is useful even when activation was
            # blocked. ``deploy_check`` itself describes only the active URL.
            manifest.extra["latest_deploy_check"] = dict(deploy_check)
        if ok and url:
            manifest.extra["live_url"] = url
            if isinstance(deploy_check, dict):
                manifest.extra["deploy_check"] = dict(deploy_check)
        record["persisted"] = True
        manifest.save(pdir)
    except Exception as exc:  # noqa: BLE001 - recording must not make deploy fail
        record["persisted"] = False
        record["persistence_error"] = str(exc)[:160]
    return record


def rollback_deployment(
    project_dir: str | Path,
    *,
    reason: str = "",
    deployment_index: int | None = None,
) -> dict[str, Any]:
    """Move the manifest's live URL pointer to an earlier deployment.

    This function never invokes a provider and never claims that remote traffic,
    aliases, releases, or infrastructure changed. ``ok`` reports only whether the
    local manifest pointer was updated; ``remote_rollback_performed`` is always
    false. Provider rollback requires provider-specific immutable deployment IDs,
    which legacy deployment records do not contain.
    """
    ts = time()
    record: dict[str, Any] = {
        "ok": False,
        "ts": ts,
        "reason": str(reason or ""),
        "from_url": "",
        "to_url": "",
        "operation": "manifest_pointer",
        "status": "not_started",
        "persisted": False,
        "remote_rollback_performed": False,
    }
    try:
        from skyn3t.studio.manifest import BuildManifest

        pdir = Path(project_dir)
        manifest = BuildManifest.load(pdir)
        if manifest is None:
            record["error"] = "manifest not found"
            return record
        deployments = manifest.extra.get("deployments")
        if not isinstance(deployments, list) or len(deployments) < 2:
            record["error"] = "at least two deployments are required to roll back"
            return record

        candidates = [
            idx for idx, dep in enumerate(deployments)
            if (
                isinstance(dep, dict)
                and dep.get("url")
                and dep.get("ok", True)
                and not dep.get("manifest_pointer_rolled_back")
            )
        ]
        if not candidates:
            record["error"] = "no active deployment found"
            return record
        if deployment_index is not None and not 0 <= deployment_index < len(deployments):
            record["status"] = "invalid_selection"
            record["error"] = "deployment_index is out of range"
            return record

        live_url = str(manifest.extra.get("live_url") or "")
        active = [
            idx for idx in candidates
            if bool(deployments[idx].get("manifest_pointer_active"))
        ]
        matching_live = [
            idx for idx in candidates
            if str(deployments[idx].get("url") or "") == live_url
        ]
        current_idx = active[-1] if active else (
            matching_live[-1] if matching_live else candidates[-1]
        )
        if deployment_index is not None and deployment_index != current_idx:
            record["status"] = "invalid_selection"
            record["error"] = "selected deployment is not the active manifest pointer"
            return record
        current = deployments[current_idx]
        if not isinstance(current, dict) or not current.get("url"):
            record["error"] = "selected deployment has no URL"
            return record
        previous = None
        previous_idx = -1
        for idx in reversed(candidates):
            if idx < current_idx:
                previous = deployments[idx]
                previous_idx = idx
                break
        if not isinstance(previous, dict) or not previous.get("url"):
            record["error"] = "no previous live deployment found"
            return record

        current["manifest_pointer_active"] = False
        current["manifest_pointer_rolled_back"] = True
        current["manifest_pointer_rolled_back_at"] = ts
        if reason:
            current["manifest_pointer_rollback_reason"] = str(reason)
        previous["manifest_pointer_active"] = True

        record.update({
            "ok": True,
            "status": "pointer_updated",
            "persisted": True,
            "from_index": current_idx,
            "to_index": previous_idx,
            "from_url": str(current.get("url") or ""),
            "to_url": str(previous.get("url") or ""),
            "target": str(previous.get("target") or ""),
            "provider": str(previous.get("provider") or ""),
            "note": "Local manifest pointer updated; no provider rollback was performed.",
        })
        rollbacks = manifest.extra.get("deployment_rollbacks")
        if not isinstance(rollbacks, list):
            rollbacks = []
        rollbacks.append(record)
        manifest.extra["deployment_rollbacks"] = rollbacks[-20:]
        manifest.extra["deployments"] = deployments[-20:]
        manifest.extra["live_url"] = record["to_url"]
        manifest.save(pdir)
    except Exception as exc:  # noqa: BLE001 - rollback records must not crash callers
        record.update({
            "ok": False,
            "status": "persistence_failed",
            "persisted": False,
            "error": str(exc)[:160],
        })
    return record


# ── Ship pillar, slice 2: token-gated REAL execution ─────────────────────────
# Everything above this line is the KEYLESS planner: it never touches the
# network and never needs a credential. This section is the complement — it
# executes one plan against its real host, ONLY when the operator holds the
# provider token in their own environment. Posture (same as the rest of the
# repo): the token crosses via the subprocess ENVIRONMENT, never argv (process
# lists leak); the subprocess env is scrubbed by ``filter_env`` so only the one
# provider token is added back; every byte of captured output is masked before
# it is printed or persisted; and nothing here runs without the CLI's explicit
# ``--execute`` consent flow (lab autonomy / --yes / interactive confirm).

# plan target -> (official CLI binary, operator token env var, install hint).
# Covers every URL-serving host the planner emits that has a token-gated
# official CLI: Cloudflare Pages (wrangler), Vercel, Fly.io (flyctl), Netlify.
EXECUTABLE_PROVIDERS: dict[str, tuple[str, str, str]] = {
    "cloudflare-pages": (
        "wrangler",
        "CLOUDFLARE_API_TOKEN",
        "install wrangler: npm install -g wrangler",
    ),
    "vercel": (
        "vercel",
        "VERCEL_TOKEN",
        "install the Vercel CLI: npm install -g vercel",
    ),
    "fly": (
        "flyctl",
        "FLY_API_TOKEN",
        "install flyctl: https://fly.io/docs/flyctl/install/",
    ),
    "netlify": (
        "netlify",
        "NETLIFY_AUTH_TOKEN",
        "install the Netlify CLI: npm install -g netlify-cli",
    ),
}

# provider -> canonical hostname suffix of its live deploy URLs. CLI output
# mixes docs/dashboard/support links with the real URL, so only a suffixed
# https URL is accepted as the deploy URL.
_EXECUTE_URL_SUFFIXES: dict[str, tuple[str, ...]] = {
    "cloudflare-pages": (".pages.dev",),
    "vercel": (".vercel.app",),
    "fly": (".fly.dev",),
    "netlify": (".netlify.app",),
}

_LIVE_URL_RE = re.compile(r"https?://[^\s'\"<>]+", re.IGNORECASE)

# Flags a provider CLI could accept a credential through. A plan command
# carrying one is rejected outright: tokens cross via the environment ONLY.
_CREDENTIAL_ARGV_FLAGS = frozenset({
    "-t", "--access-token", "--api-key", "--auth", "--auth-token", "--token",
})


def executable_provider(target: str) -> tuple[str, str, str] | None:
    """The ``(CLI, token env var, install hint)`` for a plan target, or ``None``
    when ``--execute`` is not wired for it (the keyless plan is all you get)."""
    return EXECUTABLE_PROVIDERS.get((target or "").strip().lower())


def resolve_deploy_token(
    target: str,
    env: Mapping[str, str] | None = None,
) -> tuple[str, str]:
    """Discover the operator's deploy token for ``target`` in the environment.

    Returns ``(token, env_var_name)``; the token is ``""`` when unset — the
    caller refuses to execute and names the exact env var to set. No partial
    behavior: an absent token is an error, never a silent fallback to ambient
    CLI credentials cached on disk.
    """
    spec = executable_provider(target)
    if spec is None:
        return "", ""
    _, env_name, _ = spec
    source = env if env is not None else os.environ
    return (source.get(env_name) or "").strip(), env_name


def deploy_execution_blocker(
    project_dir: str | Path,
    plan: DeployPlan,
    target: str,
    *,
    env: Mapping[str, str] | None = None,
) -> str:
    """Deterministic ``--execute`` preflight. Returns ``""`` when execution may
    proceed, else the exact human-actionable blocker: the env var to set, the
    CLI install hint, or why the target is unsupported. Pure — no subprocess,
    no writes, no network."""
    spec = executable_provider(target)
    if spec is None:
        supported = ", ".join(sorted(EXECUTABLE_PROVIDERS))
        return (
            f"--execute is not wired for target '{target}' "
            f"(supported: {supported})"
        )
    cli, _, install_hint = spec
    token, env_name = resolve_deploy_token(target, env=env)
    if not token:
        return f"set {env_name} to execute a {target} deploy"
    if _resolve_provider_cli(project_dir, cli) is None:
        return f"'{cli}' is not installed (outside the project) — {install_hint}"
    return ""


def _resolve_provider_cli(project_dir: str | Path, cli: str) -> Path | None:
    """Resolve the real provider CLI, rejecting project-controlled executables.

    A generated project must never choose the binary that receives a production
    token, even when PATH contains the project directory.
    """
    raw = shutil.which(cli)
    if not raw:
        return None
    try:
        resolved = Path(raw).resolve(strict=True)
    except OSError:
        return None
    try:
        resolved.relative_to(Path(project_dir).resolve(strict=True))
        return None
    except (ValueError, OSError):
        pass
    return resolved if resolved.is_file() else None


def _mask_deploy_text(text: str, token: str) -> str:
    """Mask the operator token (explicit replace — its env-var name family is
    not in the mask registry) plus every registered secret via
    :func:`skyn3t.security.secrets.mask_secrets`."""
    from skyn3t.security.secrets import MASKED, mask_secrets

    out = (text or "").replace(token, MASKED) if token else (text or "")
    return mask_secrets(out)


def extract_live_url(text: str, target: str) -> str:
    """Parse the deploy URL a provider CLI printed: the LAST https URL under the
    provider's canonical hostname suffix (CLIs print docs/dashboard links
    first; the live URL comes last). ``""`` when nothing qualifies."""
    suffixes = _EXECUTE_URL_SUFFIXES.get((target or "").strip().lower(), ())
    if not suffixes:
        return ""
    for raw in reversed(_LIVE_URL_RE.findall(text or "")):
        candidate = raw.rstrip(".,;:!?)]}")
        try:
            parsed = urlsplit(candidate)
            hostname = (parsed.hostname or "").lower().rstrip(".")
            port = parsed.port
        except ValueError:
            continue
        if (
            parsed.scheme == "https"
            and not parsed.username
            and not parsed.password
            and port in (None, 443)
            and any(hostname.endswith(suffix) for suffix in suffixes)
        ):
            return f"https://{hostname}"
    return ""


def execute_deploy(
    project_dir: str | Path,
    plan: DeployPlan,
    target: str,
    *,
    token: str,
    timeout: float = 600.0,
) -> dict[str, Any]:
    """Execute ``plan`` against its real host via the official provider CLI.

    The caller (CLI ``--now --execute``) has already obtained explicit consent
    and the token from :func:`resolve_deploy_token`. The token is injected into
    a SCRUBBED subprocess environment (never argv), all captured output is
    masked with the token + :func:`mask_secrets`, and the returned dict is safe
    to print or persist. Never raises; failure is ``{"ok": False, "error": ...}``.
    """
    result: dict[str, Any] = {
        "ok": False,
        "url": "",
        "target": str(target or ""),
        "kind": str(getattr(plan, "kind", "") or ""),
        "status": "not_started",
        "argv": [],
        "returncode": None,
        "output_tail": "",
        "error": "",
    }
    spec = executable_provider(target)
    if spec is None:
        supported = ", ".join(sorted(EXECUTABLE_PROVIDERS))
        result["error"] = (
            f"--execute is not wired for target '{target}' (supported: {supported})"
        )
        return result
    cli, token_env, _ = spec
    if not token:
        result["error"] = f"set {token_env} to execute a {target} deploy"
        return result
    try:
        argv = shlex.split(str(getattr(plan, "command", "") or ""))
    except ValueError as exc:
        result["status"] = "invalid_plan"
        result["error"] = f"invalid deploy command quoting: {exc}"
        return result
    # Only the planner's own command for THIS provider may receive the token:
    # the entrypoint must be the provider CLI and carry no credential flags.
    if not argv or Path(argv[0]).stem.lower() != cli:
        result["status"] = "invalid_plan"
        result["error"] = f"plan command is not a {cli} invocation"
        return result
    if any(
        str(part).split("=", 1)[0].lower() in _CREDENTIAL_ARGV_FLAGS for part in argv[1:]
    ):
        result["status"] = "invalid_plan"
        result["error"] = (
            "deploy command carries a credential flag; tokens cross via the "
            "environment only"
        )
        return result
    resolved = _resolve_provider_cli(project_dir, cli)
    if resolved is None:
        result["status"] = "cli_unavailable"
        result["error"] = (
            f"'{cli}' is not installed (outside the project) — {spec[2]}"
        )
        return result
    argv[0] = str(resolved)
    result["argv"] = [str(part) for part in argv]

    # Least-privilege env: scrub every secret, strip ALL provider tokens, then
    # add back only the one token this provider's CLI reads.
    from skyn3t.security.secrets import filter_env

    deploy_env = filter_env(
        os.environ,
        extra_block=[spec[1] for spec in EXECUTABLE_PROVIDERS.values()],
    )
    deploy_env[token_env] = token
    deploy_env["CI"] = "true"
    deploy_env["NO_COLOR"] = "1"

    try:
        proc = subprocess.run(
            argv,
            cwd=str(project_dir),
            capture_output=True,
            text=True,
            timeout=timeout,
            env=deploy_env,
        )
    except Exception as exc:  # noqa: BLE001 - an exec failure is a failed deploy
        result["status"] = "execution_error"
        result["error"] = _mask_deploy_text(str(exc)[:500], token)
        return result
    result["returncode"] = proc.returncode
    combined = "\n".join(part for part in (proc.stdout, proc.stderr) if part)
    masked = _mask_deploy_text(combined, token)
    result["output_tail"] = masked.strip()[-500:]
    if proc.returncode != 0:
        result["status"] = "deploy_failed"
        result["error"] = (
            f"{cli} exited {proc.returncode}: {masked.strip()[-300:] or 'no output'}"
        )
        return result
    url = extract_live_url(combined, target)
    if url and len(token) >= 6 and token in url:
        url = ""  # a URL echoing the credential is not a deploy URL
    if not url:
        result["status"] = "succeeded_url_unresolved"
        result["error"] = f"{cli} succeeded but printed no {target} URL"
        return result
    result.update({"ok": True, "url": url, "status": "succeeded"})
    return result


def record_deploy_outcome(
    project_dir: str | Path,
    *,
    kind: str,
    url: str,
    verified: bool,
) -> dict[str, Any]:
    """Record the latest REAL deploy execution in ``manifest.extra["deploy"]``.

    Single-slot "current live deploy" summary — ``{kind, url, verified, at}``
    with bounded, masked strings (the append-only evidence trail stays in
    ``extra["deployments"]`` via :func:`record_deployment`). Never raises.
    """
    from skyn3t.security.secrets import mask_secrets

    entry = {
        "kind": str(kind or "")[:40],
        "url": mask_secrets(str(url or ""))[:200],
        "verified": bool(verified),
        "at": datetime.now(UTC).isoformat(timespec="seconds"),
    }
    try:
        from skyn3t.studio.manifest import BuildManifest

        pdir = Path(project_dir)
        manifest = BuildManifest.load(pdir)
        if manifest is None:
            return {**entry, "persisted": False, "persistence_error": "manifest not found"}
        manifest.extra["deploy"] = dict(entry)
        manifest.save(pdir)
        return {**entry, "persisted": True}
    except Exception as exc:  # noqa: BLE001 - recording must not fail a deploy
        return {**entry, "persisted": False, "persistence_error": str(exc)[:160]}
