"""The Ship pillar — turn a proven build into a concrete plan to go live.

skyn3t builds + proves + previews LOCALLY (``app_runner`` is localhost-only).
This module classifies a build and emits a KEYLESS, one-command deploy plan:
the right hosts, the exact command, and — for server stacks — a ready Dockerfile.
No token, no network: it is the honest "…and here's how it ships" answer for
every stack the builder can produce, or an honest "not a hosted app" verdict.

Registry-driven (the same idiom as ``core.stacks``): every builder stack maps to
a deploy KIND, so a new stack is never silently un-shippable. Real, token-gated
one-command deploy (invoking the emitted command) is a later slice; this is the
foundation and it is fully offline-provable.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# stack (agent vocab + planner aliases) -> deploy kind. Every KNOWN_STACKS entry
# is present (a drift test asserts it). Kinds:
#   static    — a built static bundle → a static host (Cloudflare Pages/Netlify)
#   node_ssr  — a full-stack Node app → Vercel / a Node container
#   container — an HTTP server → Fly / Railway / Render (Dockerfile emitted)
#   artifact  — not a hosted URL: a publishable/runnable binary or package
#   mobile    — an app binary → Expo EAS
DEPLOY_KIND: dict[str, str] = {
    # static-hostable web builds
    "react_vite": "static", "react": "static",
    "static_html": "static", "static": "static",
    "astro": "static", "phaser": "static",
    # full-stack Node (SSR/routing) — not a plain static drop
    "nextjs": "node_ssr", "next": "node_ssr", "remix": "node_ssr",
    # HTTP servers → container
    "fastapi": "container", "rag": "container", "workflow": "container",
    "node_express": "container", "express": "container",
    # not web-hosted: distributable artifacts
    "python_cli": "artifact", "python": "artifact", "cli": "artifact",
    "agent_pack": "artifact", "mcp": "artifact",
    "swift": "artifact", "tauri": "artifact", "desktop": "artifact",
    # mobile app binary
    "react_native": "mobile",
}

_PY_DOCKERFILE = (
    "# Generated by skyn3t — a container image for this FastAPI/Python server.\n"
    "FROM python:3.11-slim\n"
    "WORKDIR /app\n"
    "COPY requirements.txt ./\n"
    "RUN pip install --no-cache-dir -r requirements.txt\n"
    "COPY . .\n"
    "# Platforms (Fly/Railway/Render) inject $PORT; main.py reads it.\n"
    "ENV PORT=8080\n"
    "EXPOSE 8080\n"
    'CMD ["python", "main.py"]\n'
)

_NODE_DOCKERFILE = (
    "# Generated by skyn3t — a container image for this Node server.\n"
    "FROM node:20-slim\n"
    "WORKDIR /app\n"
    "COPY package*.json ./\n"
    "RUN npm ci --omit=dev || npm install --omit=dev\n"
    "COPY . .\n"
    "ENV PORT=8080\n"
    "EXPOSE 8080\n"
    'CMD ["node", "src/index.js"]\n'
)


@dataclass(slots=True)
class DeployPlan:
    """A concrete, keyless plan to put a build on the internet (or distribute it)."""

    deployable: bool = False
    kind: str = "none"
    targets: list[str] = field(default_factory=list)
    command: str = ""
    build_command: str = ""
    output_dir: str = "."
    artifacts: dict[str, str] = field(default_factory=dict)
    serves_url: bool = False
    notes: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "deployable": self.deployable,
            "kind": self.kind,
            "targets": list(self.targets),
            "command": self.command,
            "build_command": self.build_command,
            "output_dir": self.output_dir,
            "artifacts": dict(self.artifacts),
            "serves_url": self.serves_url,
            "notes": self.notes,
        }


def _normalize(stack: str) -> str:
    s = (stack or "").strip().lower()
    if s in DEPLOY_KIND:
        return s
    try:
        from skyn3t.agents._common import _normalize_stack

        return _normalize_stack(s) or s
    except Exception:  # noqa: BLE001 - deploy planning must never raise
        return s


def _detect_kind(project_dir: Path, stack: str) -> str:
    """The deploy kind for a stack; when the stack is unknown/empty, fall back to
    content detection via the same run-spec the local preview uses."""
    norm = _normalize(stack)
    if norm in DEPLOY_KIND:
        return DEPLOY_KIND[norm]
    try:
        from skyn3t.studio.app_runner import build_run_spec

        spec = build_run_spec(project_dir, stack)
    except Exception:  # noqa: BLE001
        spec = None
    if spec is None:
        return "none"
    if spec.kind == "python_web":
        return "container"
    if spec.kind == "static":
        return "static"
    if spec.kind == "node":
        return "node_ssr" if (project_dir / "next.config.js").exists() else "static"
    return "none"


def _has_build_script(project_dir: Path) -> bool:
    pkg = project_dir / "package.json"
    if not pkg.exists():
        return False
    try:
        scripts = (json.loads(pkg.read_text(encoding="utf-8")) or {}).get("scripts") or {}
    except (OSError, ValueError):
        return False
    return "build" in scripts


def plan_deploy(project_dir: str | Path, stack: str = "", *, target: str | None = None) -> DeployPlan:
    """Classify ``project_dir`` and return a keyless :class:`DeployPlan`. Never
    raises; a missing dir or unknown stack still yields a sane plan."""
    try:
        pdir = Path(project_dir)
        kind = _detect_kind(pdir, stack)

        if kind == "static":
            built = _has_build_script(pdir)
            return DeployPlan(
                deployable=True, kind="static", serves_url=True,
                targets=["cloudflare-pages", "netlify", "vercel"],
                output_dir="dist" if built else ".",
                build_command="npm run build" if built else "",
                command="npx wrangler pages deploy " + ("dist" if built else "."),
                notes="A static bundle — deploy the built output to any static host.",
            )

        if kind == "node_ssr":
            return DeployPlan(
                deployable=True, kind="node_ssr", serves_url=True,
                targets=["vercel", "railway", "fly"],
                output_dir=".", build_command="npm run build",
                command="npx vercel deploy --prebuilt",
                notes="A full-stack Node app — Vercel is zero-config; Railway/Fly work via a Node container.",
            )

        if kind == "container":
            norm = _normalize(stack)
            dockerfile = _NODE_DOCKERFILE if norm in ("node_express", "express") else _PY_DOCKERFILE
            return DeployPlan(
                deployable=True, kind="container", serves_url=True,
                targets=["fly", "railway", "render"],
                output_dir=".", build_command="",
                command="fly launch --dockerfile Dockerfile --now",
                artifacts={"Dockerfile": dockerfile},
                notes="An HTTP server — ships as a container. Set any keys as platform secrets.",
            )

        if kind == "mobile":
            return DeployPlan(
                deployable=True, kind="mobile", serves_url=False,
                targets=["expo-eas"], output_dir=".", build_command="",
                command="eas build --platform all",
                notes="A mobile app — build stores/installable binaries via Expo EAS.",
            )

        if kind == "artifact":
            norm = _normalize(stack)
            if norm in ("python_cli", "python", "cli", "mcp"):
                targets = ["pypi", "github-release"]
                command = "python -m build && python -m twine upload dist/*"
                output = "dist"
            else:  # agent_pack, swift, tauri, desktop
                targets = ["github-release"]
                command = "gh release create v0.1.0 <built-artifact>"
                output = "."
            return DeployPlan(
                deployable=True, kind="artifact", serves_url=False,
                targets=targets, output_dir=output, build_command="",
                command=command,
                notes="Not a hosted URL — a distributable package/binary. Publish, don't serve.",
            )

        return DeployPlan(deployable=False, kind="none",
                          notes="No hosted deploy path detected for this build.")
    except Exception as exc:  # noqa: BLE001 - a planner must never break a build
        return DeployPlan(deployable=False, kind="none", notes=f"deploy planning error: {exc}")


def write_deploy_artifacts(plan: DeployPlan, project_dir: str | Path) -> list[str]:
    """Write the plan's artifacts (e.g. a Dockerfile) into the project — but
    NEVER clobber a user-authored file of the same name. Returns the names
    written. Never raises."""
    written: list[str] = []
    pdir = Path(project_dir)
    for name, content in (plan.artifacts or {}).items():
        target = pdir / name
        if target.exists():
            continue  # non-destructive: respect a hand-authored file
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8")
            written.append(name)
        except OSError:
            continue
    return written
