"""Conservative web product-polish gate.

Blocking checks are intentionally structural, not aesthetic: they block only UI
web builds too thin to be credible products. A second class of checks — the
AI-default look (purple gradients, Inter-first type, glassmorphism clusters,
decorative emoji, viewport heroes, identical card grids, placeholder copy,
bounce easing, hand-rolled styled primitives) — is reported as advisory
WARNINGS only: weak, brief-dependent signals that must never fail a build.
The two most invitation-dependent detectors (emoji, identical card grid) are
suppressed when the brief explicitly invites that aesthetic (playful/sticker/
y2k, or gallery/portfolio/card-grid wording). Warnings are recorded on the
manifest and surfaced via the API for the operator; they do NOT feed the
repair loop within a run (the gate runs after the final repair pass).
"""

from __future__ import annotations

import re
from collections import Counter
from pathlib import Path
from typing import Any

from skyn3t.core.stacks import UI_WEB_STACKS

_UI_STACKS = UI_WEB_STACKS - {"phaser"}
_SUFFIXES = {
    ".html", ".jsx", ".tsx", ".js", ".ts", ".astro", ".vue", ".svelte", ".css",
}
_SKIP_DIRS = {"node_modules", ".next", "dist", "build", "out"}
_HEADING_RE = re.compile(r"<h1\b|className=.*text-[34]|font-size\s*:\s*(?:[2-9]rem|[3-9][0-9]px)", re.I | re.S)
_ACTION_RE = re.compile(r"<(?:button|a|input|select|textarea)\b|onClick=|href=", re.I)
_STYLE_RE = re.compile(r"className=|class=|background|border-radius|box-shadow|grid|flex|--[a-z0-9-]+:", re.I)
_CSS_IMPORT_RE = re.compile(
    r"\bimport\s+(?:[^;\n]*?\s+from\s+)?['\"][^'\"]+\.css(?:[?#][^'\"]*)?['\"]",
    re.I,
)
_CSS_LINK_RE = re.compile(
    r"<link\b(?=[^>]*\brel\s*=\s*['\"]stylesheet['\"])(?=[^>]*\bhref\s*=\s*['\"][^'\"]+\.css(?:[?#][^'\"]*)?['\"])[^>]*>",
    re.I,
)
# Decorative pictographs are a WEAK signal of placeholder UI: the range also
# matches legitimate glyphs (star ratings, hamburger menus, card suits) and a
# brief may explicitly ask for emoji. Advisory warning only — never blocking.
_DECORATIVE_EMOJI_RE = re.compile(r"[\U0001F000-\U0001FAFF\u2600-\u26FF]")

# AI-default-look detectors. All WEAK signals -> advisory warnings only, never
# blocking issues: a brief may legitimately ask for any of these, and the gate's
# job is to record the smell, not to veto taste. Each warning is phrased as a
# fix hint so it is actionable when surfaced to the improve loop.
# Purple/indigo/violet gradient — the canonical "generated by an LLM" banner.
# CSS form: linear-gradient(... #6366f1 ...). Tailwind form: from-indigo-500 etc.
_AI_GRADIENT_CSS_RE = re.compile(
    r"linear-gradient\([^)]*(?:#(?:6366f1|4f46e5|4338ca|7c3aed|8b5cf6|6d28d9|a855f7|d946ef)\b"
    r"|\bindigo\b|\bviolet\b|\bpurple\b)",
    re.I,
)
_AI_GRADIENT_TW_RE = re.compile(r"\b(?:from|via|to)-(?:indigo|violet|purple|fuchsia)-\d{3}\b")
# Inter as the named face of the app (font-family or a Google Fonts request).
_INTER_FIRST_RE = re.compile(r"font-family\s*:\s*['\"]?Inter\b|family=Inter\b", re.I)
# Glassmorphism card cluster: frosted blur + big radius + big shadow together.
_BACKDROP_BLUR_RE = re.compile(r"backdrop-blur\b|backdrop-filter\s*:\s*blur", re.I)
_ROUNDED_XL_RE = re.compile(r"rounded-(?:2xl|3xl)\b|border-radius\s*:\s*(?:1\.5rem|2rem|24px|32px)\b")
_SHADOW_XL_RE = re.compile(r"shadow-(?:xl|2xl)\b|box-shadow\s*:\s*0\s+(?:2[0-9]|[3-9][0-9])px")
# Brief-aware suppression: an INVITED look is not the AI-default look. A brief
# that asks for playful emoji/stickers, or for a gallery/card grid, must not be
# flagged for shipping exactly that. Neutral when the brief is unknown (callers
# that don't have it behave exactly as before).
_PLAYFUL_INVITE_RE = re.compile(
    r"\b(?:emoji|emojis|sticker|stickers|badge|badges|playful|kawaii|y2k|retro)\b", re.I
)
_GRID_INVITE_RE = re.compile(
    r"\b(?:gallery|galleries|masonry|portfolio|card\s?grid|cards)\b", re.I
)
# Full-viewport hero: h-screen/min-h-screen or 100(v|d)vh sizing in a file
# that also mentions hero/header. Weak signal — full-bleed heroes are a
# legitimate design choice and the class may sit on a non-hero element.
# Advisory warning only.
_VIEWPORT_HERO_CLASS_RE = re.compile(r"\b(?:min-)?h-screen\b")
_VIEWPORT_HERO_CSS_RE = re.compile(r"(?:min-)?height\s*:\s*100d?vh\b")
_HERO_CONTEXT_RE = re.compile(r"hero|<header", re.I)
# Identical repeated card grid: the same class attribute containing 'card'
# stamped on 3+ elements reads as generated filler. Weak signal — design
# systems intentionally reuse one card class. Advisory warning only.
_CARD_CLASS_RE = re.compile(r"class(?:Name)?\s*=\s*['\"][^'\"]*card[^'\"]*['\"]", re.I)
# Placeholder copy (John Doe, Lorem ipsum, ...) means real content was never
# written. Weak signal — a brief may legitimately demo with personas.
# Advisory warning only.
_PLACEHOLDER_COPY_RE = re.compile(r"john doe|jane doe|acme corp|lorem ipsum", re.I)
# Bounce/elastic easing: cubic-bezier overshoot (any component > 1) or
# bounce/elastic keywords in a transition/animation context read as template
# defaults. Weak signal — playful briefs may ask for springy motion.
# Advisory warning only.
_BEZIER_RE = re.compile(r"cubic-bezier\(([^)]*)\)", re.I)
_BEZIER_NUM_RE = re.compile(r"-?\d+(?:\.\d+)?")
_BOUNCE_KW_RE = re.compile(r"\b(?:bounce|elastic)\b", re.I)
_MOTION_CONTEXT_RE = re.compile(r"transition|animation", re.I)
# Hand-rolled styled <button> next to the scaffold's ui primitives means the
# builder ignored its own component kit. Weak signal — a one-off element may
# not deserve a shared primitive. Advisory warning only.
_STYLED_BUTTON_RE = re.compile(
    r"<button\b[^>]*?className\s*=\s*[\"'{][^>]*?\b(?:bg-|rounded-|px-|py-)",
    re.I,
)
_SCAFFOLD_UI_FILES = ("src/components/ui.jsx", "src/components/ui.tsx")


def check_web_polish(project_dir: str | Path, stack: str = "", brief: str = "") -> dict[str, Any]:
    try:
        low = (stack or "").lower()
        if low == "phaser":
            return {"ok": True, "skipped": True, "issues": [], "checked": []}
        if low and low not in _UI_STACKS:
            return {"ok": True, "skipped": True, "issues": [], "checked": []}
        root = Path(project_dir)
        if not root.is_dir():
            return {"ok": True, "skipped": True, "issues": [], "checked": []}
        # An invited look is not the AI-default look: suppress the playful/grid
        # warnings when the brief explicitly asks for that aesthetic.
        playful_invited = bool(_PLAYFUL_INVITE_RE.search(brief or ""))
        grid_invited = bool(_GRID_INVITE_RE.search(brief or ""))
        checked: list[str] = []
        corpus: list[str] = []
        markup: list[str] = []
        stylesheets: list[str] = []
        for path in root.rglob("*"):
            if any(part in _SKIP_DIRS for part in path.parts):
                continue
            if path.is_file() and path.suffix.lower() in _SUFFIXES:
                checked.append(path.relative_to(root).as_posix())
                content = path.read_text(encoding="utf-8", errors="replace")[:10000]
                corpus.append(content)
                if path.suffix.lower() == ".css":
                    stylesheets.append(path.relative_to(root).as_posix())
                else:
                    markup.append(content)
        if not checked:
            return {"ok": True, "skipped": True, "issues": [], "checked": []}
        text = "\n".join(corpus)
        markup_text = "\n".join(markup)
        issues: list[str] = []
        warnings: list[str] = []
        if not _HEADING_RE.search(text):
            issues.append("no primary heading or hero-scale title detected")
        if not _ACTION_RE.search(text):
            issues.append("no user action/link/form control detected")
        if not _STYLE_RE.search(text):
            issues.append("no meaningful styling/layout signal detected")
        emoji_hits = _DECORATIVE_EMOJI_RE.findall(markup_text)
        if emoji_hits and not playful_invited:
            warnings.append(
                f"decorative emoji glyphs detected in UI source ({len(emoji_hits)})"
            )
        if _AI_GRADIENT_CSS_RE.search(text) or _AI_GRADIENT_TW_RE.search(text):
            warnings.append(
                "AI-default indigo/violet gradient detected — restyle with a "
                "palette that fits this brief"
            )
        if _INTER_FIRST_RE.search(text):
            warnings.append(
                "Inter-first typography detected — choose a font stack that fits "
                "this product instead of the AI default"
            )
        if (len(_BACKDROP_BLUR_RE.findall(text)) >= 2
                and _ROUNDED_XL_RE.search(text) and _SHADOW_XL_RE.search(text)):
            warnings.append(
                "glassmorphism card cluster detected (backdrop-blur + rounded-2xl "
                "+ shadow-xl) — simplify surfaces"
            )
        for content in corpus:
            if ((_VIEWPORT_HERO_CLASS_RE.search(content)
                    or _VIEWPORT_HERO_CSS_RE.search(content))
                    and _HERO_CONTEXT_RE.search(content)):
                warnings.append(
                    "full-viewport hero detected — let content size the first screen"
                )
                break
        card_attrs = _CARD_CLASS_RE.findall(markup_text)
        if card_attrs and not grid_invited and Counter(card_attrs).most_common(1)[0][1] >= 3:
            warnings.append(
                "identical repeated card grid — vary the composition"
            )
        placeholder = _PLACEHOLDER_COPY_RE.search(markup_text)
        if placeholder:
            warnings.append(
                f"placeholder copy detected ('{placeholder.group(0)}') — "
                "replace with real content"
            )
        for content in corpus:
            overshoot = any(
                float(n) > 1
                for bezier in _BEZIER_RE.findall(content)
                for n in _BEZIER_NUM_RE.findall(bezier)
            )
            if overshoot or (_BOUNCE_KW_RE.search(content)
                             and _MOTION_CONTEXT_RE.search(content)):
                warnings.append(
                    "bounce/elastic easing reads as a template — use ease-out "
                    "with 100-300ms durations"
                )
                break
        if any(p in _SCAFFOLD_UI_FILES for p in checked):
            for rel, content in zip(checked, corpus):
                if rel in _SCAFFOLD_UI_FILES:
                    continue
                if rel.endswith((".jsx", ".tsx")) and _STYLED_BUTTON_RE.search(content):
                    warnings.append(
                        "hand-rolled styled <button> outside the scaffold "
                        "primitives — compose src/components/ui.* instead"
                    )
                    break
        if stylesheets:
            if not (_CSS_IMPORT_RE.search(markup_text) or _CSS_LINK_RE.search(markup_text)):
                issues.append("stylesheets exist but no CSS import or stylesheet link was found")
        return {
            "ok": not issues,
            "skipped": False,
            "issues": issues,
            "warnings": warnings,
            "checked": checked[:100],
        }
    except Exception as exc:  # noqa: BLE001
        return {"ok": True, "skipped": True, "issues": [], "warnings": [str(exc)[:160]], "checked": []}
