"""Execution backend abstraction — docker if available, else LOUD inline.

Design rule #4 (safe by default): code generated by agents should run in a
container. If docker is unavailable we MUST NOT silently fall back to a
silent in-process ``exec`` — instead we run the command in a child subprocess
(never in-process), after emitting a LOUD warning so the operator knows the
sandbox is degraded.

Backend selection honours ``Settings.execution_backend`` (auto|docker|inline)
and ``sandbox_*`` knobs. ``docker`` is an optional heavy dep, guarded so the
module always imports (design rule #3, #6). Import has zero side effects: docker
is only contacted when you actually :meth:`run` or call :func:`detect_backend`.
"""

from __future__ import annotations

import asyncio
import shlex
import shutil
import warnings
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Sequence

try:
    import structlog

    _log = structlog.get_logger(__name__)
except Exception:  # pragma: no cover - defensive
    _log = None  # type: ignore[assignment]

# Optional heavy dep — guarded (design rule #3).
try:
    import docker as _docker  # type: ignore

    _HAS_DOCKER_SDK = True
except Exception:  # pragma: no cover - dep usually absent
    _docker = None  # type: ignore[assignment]
    _HAS_DOCKER_SDK = False


def _warn(msg: str) -> None:
    """Emit a LOUD warning via logger, stdlib warnings, and stderr."""
    if _log:
        _log.warning("execution.degraded", message=msg)
    try:
        warnings.warn(msg, RuntimeWarning, stacklevel=2)
    except Exception:  # pragma: no cover - defensive
        pass


@dataclass(slots=True)
class ExecResult:
    exit_code: int
    stdout: str
    stderr: str
    backend: str
    timed_out: bool = False
    command: str = ""

    @property
    def ok(self) -> bool:
        return self.exit_code == 0 and not self.timed_out


def docker_available() -> bool:
    """True only if the docker SDK is importable AND the daemon answers."""
    if not _HAS_DOCKER_SDK:
        return False
    try:
        client = _docker.from_env()  # type: ignore[union-attr]
        client.ping()
        return True
    except Exception:  # noqa: BLE001
        return False


def detect_backend(preference: str = "auto") -> str:
    """Resolve a concrete backend ('docker' or 'inline') from a preference."""
    pref = (preference or "auto").lower()
    if pref == "docker":
        if docker_available():
            return "docker"
        _warn(
            "execution_backend='docker' requested but Docker is unavailable; "
            "falling back to INLINE subprocess execution. Generated code will "
            "run on the host with reduced isolation."
        )
        return "inline"
    if pref == "inline":
        return "inline"
    # auto
    return "docker" if docker_available() else "inline"


@dataclass(slots=True)
class ExecutionBackend:
    """Run commands in docker when possible, otherwise a child subprocess.

    Never executes in-process. The inline path uses ``asyncio.create_subprocess``
    so a runaway command can be killed and cannot corrupt the host process.
    """

    settings: Any | None = None
    preference: str = "auto"
    image: str = "python:3.11-slim"
    _resolved: str = field(default="", init=False)
    _warned_inline: bool = field(default=False, init=False)

    def __post_init__(self) -> None:
        if self.settings is not None:
            self.preference = getattr(self.settings, "execution_backend", self.preference) or self.preference

    @property
    def backend(self) -> str:
        if not self._resolved:
            self._resolved = detect_backend(self.preference)
        return self._resolved

    async def run(
        self,
        command: Sequence[str] | str,
        *,
        workdir: Path | str | None = None,
        timeout: float = 120.0,
        env: dict[str, str] | None = None,
    ) -> ExecResult:
        cmd_list = shlex.split(command) if isinstance(command, str) else list(command)
        cmd_str = " ".join(shlex.quote(c) for c in cmd_list)
        if self.backend == "docker":
            return await self._run_docker(cmd_list, cmd_str, workdir, timeout, env)
        return await self._run_inline(cmd_list, cmd_str, workdir, timeout, env)

    # ---- docker -------------------------------------------------------
    async def _run_docker(
        self,
        cmd_list: list[str],
        cmd_str: str,
        workdir: Path | str | None,
        timeout: float,
        env: dict[str, str] | None,
    ) -> ExecResult:
        def _blocking() -> ExecResult:
            client = _docker.from_env()  # type: ignore[union-attr]
            mounts = {}
            container_wd = "/workspace"
            if workdir:
                mounts[str(Path(workdir).resolve())] = {
                    "bind": container_wd,
                    "mode": "rw",
                }
            kwargs: dict[str, Any] = {
                "command": cmd_list,
                "working_dir": container_wd if workdir else None,
                "environment": env or {},
                "volumes": mounts or None,
                "network_disabled": True,  # cheap + safe by default.
                "detach": True,
            }
            # Harden if requested.
            if self.settings is not None and getattr(self.settings, "sandbox_drop_caps", False):
                kwargs["cap_drop"] = ["ALL"]
            container = client.containers.run(self.image, **{k: v for k, v in kwargs.items() if v is not None})
            try:
                res = container.wait(timeout=timeout)
                code = int(res.get("StatusCode", 1))
                out = container.logs(stdout=True, stderr=False).decode("utf-8", "replace")
                err = container.logs(stdout=False, stderr=True).decode("utf-8", "replace")
                return ExecResult(code, out, err, "docker", command=cmd_str)
            finally:
                try:
                    container.remove(force=True)
                except Exception:  # noqa: BLE001
                    pass

        try:
            return await asyncio.to_thread(_blocking)
        except Exception as exc:  # noqa: BLE001
            _warn(f"Docker execution failed ({exc}); falling back to inline.")
            self._resolved = "inline"
            return await self._run_inline(cmd_list, cmd_str, workdir, timeout, env)

    # ---- inline (LOUD, but still out-of-process) ----------------------
    async def _run_inline(
        self,
        cmd_list: list[str],
        cmd_str: str,
        workdir: Path | str | None,
        timeout: float,
        env: dict[str, str] | None,
    ) -> ExecResult:
        if not self._warned_inline:
            _warn(
                "Running generated command via INLINE subprocess backend "
                "(no container isolation). This is a degraded sandbox — set "
                "execution_backend=docker and start Docker for safe execution."
            )
            self._warned_inline = True

        if not cmd_list:
            return ExecResult(1, "", "empty command", "inline", command=cmd_str)
        exe = cmd_list[0]
        if shutil.which(exe) is None and not Path(exe).exists():
            return ExecResult(
                127, "", f"command not found: {exe}", "inline", command=cmd_str
            )

        proc_env = None
        if env is not None:
            import os

            proc_env = {**os.environ, **env}

        try:
            proc = await asyncio.create_subprocess_exec(
                *cmd_list,
                cwd=str(workdir) if workdir else None,
                env=proc_env,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
        except Exception as exc:  # noqa: BLE001
            return ExecResult(1, "", f"spawn failed: {exc}", "inline", command=cmd_str)

        try:
            out_b, err_b = await asyncio.wait_for(proc.communicate(), timeout=timeout)
        except asyncio.TimeoutError:
            try:
                proc.kill()
            except Exception:  # noqa: BLE001
                pass
            return ExecResult(124, "", "timed out", "inline", timed_out=True, command=cmd_str)

        return ExecResult(
            int(proc.returncode or 0),
            out_b.decode("utf-8", "replace"),
            err_b.decode("utf-8", "replace"),
            "inline",
            command=cmd_str,
        )

    def describe(self) -> dict[str, Any]:
        return {
            "preference": self.preference,
            "resolved": self.backend,
            "docker_sdk": _HAS_DOCKER_SDK,
            "docker_daemon": docker_available() if self.backend == "docker" else False,
            "image": self.image,
        }
